### ISSUE TITLE
Valkyrien Warfare incompatibility.

### ISSUE THREAD

**Issue by sscards55** [Exopandora/ShoulderSurfing#10]
When shoulder surfing reloaded and valkyrien warfare are installed together, VW will override SSR's camera.

**Comment by Exopandora** [comment]
Did it work prior to version 1.16 ?

**Comment by Exopandora** [comment]
So ive looked at the code and it seems like a very specific issue for valkyrien warfare. Is tries to modifiy the same code shoulder surfing need in order to change the perspective. This can not be solved very easily.
