### ISSUE TITLE
[BUG] [1.18.2] Crosshair (Dynamic) disappears after alt-tab

### ISSUE THREAD

**Issue by INooBTooMuch** [Exopandora/ShoulderSurfing#100]
### Description

The Crosshair in Dynamic Mode disappears after alt-tabing out of minecarft and re-appears after f5.

### Steps to Reproduce

1. Have Dynamic Crosshair
2. Alt-tab out of minecraft (In Fullscreen)
3. The Crosshair disapperas, f5 to bring it back

### Expected Behavior

Not disappear

### Screenshots

![2022-12-24_11 22 01](https://user-images.githubusercontent.com/107572028/209430228-fffc9cb3-c011-48fd-99a7-cc16b05d0d25.png)
![2022-12-24_11 41 08](https://user-images.githubusercontent.com/107572028/209430240-28284254-478b-434f-83c4-77d20d3d2388.png)

### Game Logs

[Log](https://gist.github.com/INooBTooMuch/71adca7f007d673a81961921995c0220), I changed the previous log from the Champions Mod report...

### Additional Information

I have "Always" crosshair in the Shoulder Surfing Mode in Configs
Version : 
Forge : 40.1.92
Shoulder Surfing : 2.2.17

**Comment by Exopandora** [comment]
Thanks for the report. However, i cannot reproduce this issue. I suspect that it is caused by another mod. I can only investigate further, if you can find out which mod exactly is causing this behaviour.

**Comment by INooBTooMuch** [comment]
I tried finding the mod but it ended up not changing.
When I clean installed Shoulder Surfing, run the game to load the configs and exit and put the crosshair to Dynamic it still happens, maybe an issue with my [config](https://gist.github.com/INooBTooMuch/71adca7f007d673a81961921995c0220#file-config-in-comment)?

**Comment by Exopandora** [comment]
I was now able to reproduce the issue. You have to be in fullscreen for the bug to appear.

**Comment by INooBTooMuch** [comment]
I added it in the original post, just in case

**Comment by Exopandora** [comment]
I have a fix in place now. Again, thanks for the report! Do you have any other issues, problems, etc.? As a release is quite tedious for that many versions.

**Comment by INooBTooMuch** [comment]
I don't think there is anything else
But I do want to ask something, is there some kind of auto tracking/focusing used in Dynamic Crosshair ? Sometimes placing blocks to build is weird when going fast.

**Comment by Exopandora** [comment]
> I don't think there is anything else

Alright, then i'll create a release version.

> is there some kind of auto tracking/focusing used in Dynamic Crosshair ?

No, it just moves the crosshair onscreen to the hit-position of the raytrace, coming out of your head. It is calculated every frame.
