### ISSUE TITLE
[BUG] [1.19.2 Forge] Raytrace compatibility issue with Jade

### ISSUE THREAD

**Issue by soko7awen** [Exopandora/ShoulderSurfing#101]
I am having the same issue referenced in #85, but with Jade. WTHIT seems to work, but I prefer Jade.

**Comment by Exopandora** [comment]
Jade has a custom ray trace implementation and there is no customization for it. The author of WTHIT was so kind to implement such functionality for shoulder surfing. If you also want this fixed for Jade, you have make a feature request for Jade first.

**Comment by soko7awen** [comment]
Alright, I put one in. Thank you!
