### ISSUE TITLE
[mod not registering in fabric] [1.19.3 FABRIC] does not work even with forge config api port.

### ISSUE THREAD

**Issue by Cryptings** [Exopandora/ShoulderSurfing#105]
### Description

Followed all instructions did not work here is my mod pack:
![image](https://user-images.githubusercontent.com/70939650/213924918-aff65ef3-17f3-4f7b-b440-57db4c651f58.png)

### Steps to Reproduce

1. I Made sure [Fabric] is installed
2. IMade sure [Fabric API] is installed
3. I Made sure [Forge Config API Port] is installed
Manual
1. Navigate to "..\.minecraft\mods"
2. Copy the "ShoulderSurfing-Fabric-[VERSION].jar"
3. Follow the steps below
Launcher Settings
1. Select fabric as your profile
2. Launch Minecraft
3. realize its not working and don't know why

### Expected Behavior

mod does not work ):

### Screenshots

![image](https://user-images.githubusercontent.com/70939650/213924993-7a390d30-9544-4750-9dbb-602809e91ab2.png)
no F5 prespective 

### Game Logs

https://gist.github.com/Cryptings/e0f4bcbf58368eba4e26f0060776bfee

### Additional Information

please fix it this mod is so cool  and i love playing minecraft in this mod but its not working in 1.19.3 and all of my other mods are in 1.19.3 and cant downgrade because so much changed.

**Comment by Exopandora** [comment]
As you can see in screenshot 1) you downloaded the forge version, which only works for forge. Please use the [fabric version ](https://www.curseforge.com/minecraft/mc-mods/shoulder-surfing-reloaded/files/all?filter-status=1&filter-game-version=2020709689%3A7499)instead.

**Comment by Cryptings** [comment]
![image](https://user-images.githubusercontent.com/70939650/213930728-75af05b4-bb13-42f8-9e2d-b872203b3c3c.png)
thank you very much did not see other issues of the mod tbh ty very much
