### ISSUE TITLE
[BUG] [FABRIC 1.19.2] Crashed upon loading worlds

### ISSUE THREAD

**Issue by kingkuys2123** [Exopandora/ShoulderSurfing#106]
### Description

I installed this shoulder surfing reloaded mod in my private mod-pack and upon loading a world, the game crashes

### Steps to Reproduce

1. Install Shoulder Surfing Reloaded
2. Load one singleplayer world
3. Crashed

### Expected Behavior

It should load the world fine and the mod runs also fine.

### Game Logs

https://gist.github.com/kingkuys2123/e7d6822297b2dbc4801afaa196b04877

### Other Mods

Probably WTHIT? (WAILA fork)

**Comment by Exopandora** [comment]
Thank you for the report. I can't reproduce the issue. Could you please check if any other mods are involved, apart from WTHIT (it definately crashes because of the WTHIT plugin)?

**Comment by kingkuys2123** [comment]
Just discovered the cause of the crash earlier, it's not WTHIT but a WTHIT add-on/plugin [**Megane**](https://www.curseforge.com/minecraft/mc-mods/megane)

**Comment by Exopandora** [comment]
I still can't reproduce the crash. Nevertheless i made a new commit that should fix the issue. I will _try_ to create a release tomorrow.

**Comment by Exopandora** [comment]
I made a new release. Please re-open this issue if the game still crashes for you.

**Comment by kingkuys2123** [comment]
Not anymore, thanks for the fix! :)
