### ISSUE TITLE
[BUG] [1.12.2 Forge] Unlimited offsets do not work

### ISSUE THREAD

**Issue by Fall4573** [Exopandora/ShoulderSurfing#108]
First off thank you so much for your reply! I love that you're here to help <3

the good news is the third-person perspective option worked, it's now unlimited, just like my disappointment in life!

The bad news is this is what happens when I sit down

![Minecraft 1 12 2 2_6_2023 8_29_37 AM](https://user-images.githubusercontent.com/119358240/216985830-dfbb3acd-de8a-4437-964b-810a9d85d1ca.png)
![Minecraft 1 12 2 2_6_2023 8_30_22 AM](https://user-images.githubusercontent.com/119358240/216985869-bca5e38d-f297-4232-bc7f-46f6643aac0a.png)

it snaps back to the default max range of the shoulder surfing

efforts I've made to identify or fix this issue:
sitting on a horse or other entities will still allow for the max range

the chair being behind a wall is not what's causing this issue, I'm thinking perhaps it's another part of the config file I should change but have yet to figure out which one.

**Comment by Exopandora** [comment]
Valkyrien Skies sets the camera distance to excatly 15 blocks when you enter a ship. It's implemented in a way such that it overrides the complete camera positioning code when in a ship. I may be able to fix this with a workaround but that may take some time.

**Comment by Fall4573** [comment]
absolutely, let me know if you need me to buy you some lunch while you work <3 lol anything I can do to help!
