### ISSUE TITLE
attacking not working right

### ISSUE THREAD

**Issue by wictorias12** [Exopandora/ShoulderSurfing#109]
### Description

when i try to hit things when in a third person perspective i only hit them like im in the first person and not in third it wast like that before. hre is a screenshot with dynamic croshair enabled so you an see the targeting issue
1st image is when i dont have an enemy in fron of me
2st you can see that it automaticly changest to the first person way of attacking and moves my croshair
![2023-02-06_17 11 33](https://user-images.githubusercontent.com/110028932/217024319-6cfc42ef-d848-4473-bc82-2bf4c26c4555.png)
![2023-02-06_17 11 38](https://user-images.githubusercontent.com/110028932/217024613-d6a0a0e1-6765-4eca-a21f-2696f599d4e2.png)

### Steps to Reproduce

ss

### Expected Behavior

s

### Screenshots

s

### Game Logs

s

### Other Mods

s

### Additional Information

s

**Comment by Exopandora** [comment]
Please fill in all the details of the issue template, otherwise i am not able to help you.
