### ISSUE TITLE
[Suggestion] [1.19.3] Locking at entities

### ISSUE THREAD

**Issue by Taiyou06** [Exopandora/ShoulderSurfing#110]
**Describe your feature**
When pressed a keybind player's croshair will be locked at which enetity is there, like how it works in souls games, camera automatically follows the entity when moving.

**Comment by Exopandora** [comment]
Sorry for the late response. I looked at some gameplay footage and came to the conclusion that this feature is not really a suitable for shoulder surfing, Instead, this would be more of a feature for [BetterThirdPerson](https://www.curseforge.com/minecraft/mc-mods/better-third-person), which can be used in conjunction with shoulder surfing.
