### ISSUE TITLE
[FEATURE] [1.19.2] Adaptive shoulder switching.

### ISSUE THREAD

**Issue by amoooooo** [Exopandora/ShoulderSurfing#111]
**Describe your feature**
It would be nice to have an optional feature that allows the third person shoulder camera to lerp between each shoulder depending on camera context, e.g if there's a wall in the way of the current camera angle it will start to smoothly switch to the opposite shoulder, stopping and moving back if the area of the original shoulder frees up.

I can understand issues with this, such as tight corridoors and simply rotating the camera to get a better angle, but i'm imagining this working like The Division 2's camera movement.

**Comment by RaptaG** [comment]
I support this suggestion too, it's a must have

**Comment by Ethan23p** [comment]
Seconded! Probably a bit of work, but would be nice

**Comment by Exopandora** [comment]
This has somewhat been implemented in the latest release. Although a nice idea, while prototyping, I found switching shoulders entirely to be quite nauseating, which lead to the current implementation. Thanks for the suggestion!
