### ISSUE TITLE
[BUG] [1.19.2] incompatibility with Origins?

### ISSUE THREAD

**Issue by Riper67** [Exopandora/ShoulderSurfing#115]
### Description

(already reported the bug to the modpack Creators they told me to come here)
So i Downloaded a Modpack named "fantasy Minecraft" and if you select a Origin (mod: Origins) wich is small like half a block or smaller and activate F5 the char dissapears but if i open Inventory i can see my character again.

### Steps to Reproduce

1. Download The modpack?
2. Open world With the Origin pixie
3. press F5

### Expected Behavior

That It Shows My character and works?

### Screenshots

![Screenshot (19)](https://user-images.githubusercontent.com/128292643/226171444-0baf75fb-6582-4e9d-983c-3f2dab6aa76c.png)
please dont mind the other side of the screenshot 

### Game Logs

https://gist.github.com/Riper67/c8c0fa875c5545bee80967a32a17f56f
https://gist.github.com/Riper67/785fb83f4473ad44177fcf1c7f5e9085

**Comment by Exopandora** [comment]
This is due to the config option "keep camere out of head". If the camera gets closer than 0.8 block to the player, the player model will not be rendered for better visibility. If you disable this option, the player will always be visible. I will look into making the distance dependant on the size of the player model.

**Comment by Exopandora** [comment]
Related to #96

**Comment by Riper67** [comment]
and how do i disable the option or cant i?

**Comment by Riper67** [comment]
> This is due to the config option "keep camere out of head". If the camera gets closer than 0.8 block to the player, the player model will not be rendered for better visibility. If you disable this option, the player will always be visible. I will look into making the distance dependant on the size of the player model.

< How do i disable it?

**Comment by Exopandora** [comment]
The config file is located in `.minecraft/config/shouldersurfing.toml` which can be edited with any text editor. Alternatively you can configure it ingame (requires "modmenu" on fabric). Although you may have to install "configured" for the later.

**Comment by Riper67** [comment]
Thanks it fixed this issue
