### ISSUE TITLE
[FEATURE] [1.19.2] Allow the skipRenderPlayer camera distance to be configurable.

### ISSUE THREAD

**Issue by Tmktahu** [Exopandora/ShoulderSurfing#116]
**Describe your feature**
When playing Origins where your character size is smaller than normal, this mod is fantastic. But when `keepCameraOutOfHead` is enabled, the distance that it begins to hide the character is too large, causing the player rendering to always be skipped. WIthout this setting on, it can be very difficult to mine in tiny tunnels or operate next to walls.

At the moment, the value is hardcoded to `0.80` on [line 159 of ShouldRenderer.java](https://github.com/Exopandora/ShoulderSurfing/blob/8aec87c1a614ab98bc27bacfd12cbb7d9e87d8d2/common/src/main/java/com/teamderpy/shouldersurfing/client/ShoulderRenderer.java#L159).

I suggest making that a configurable value instead.

I would do it myself and put a PR together, but I'm not familiar with how to correctly initialize a new configuration option or compile the mod once the change is done.

**Comment by Exopandora** [comment]
Thanks for reporting! This issue has already been reported a few weeks ago. I was thinking about making the distance dependant on the player size (see [#115](https://github.com/Exopandora/ShoulderSurfing/issues/115#issuecomment-1475220687)), but i never came around to actually test it. I will try to make it in the coming days.

**Comment by Exopandora** [comment]
This has been addressed in SSR release 2.3.2. Thanks again for the report.
