### ISSUE TITLE
Add config 

### ISSUE THREAD

**Issue by tacocoma** [Exopandora/ShoulderSurfing#118]
Please add a config file to skip angles or separate the vanilla camera angles to separate keys. I have another mod, auto thirdperson, that has a config option for removing the front facing camera entirely but this mod overrides that feature and adds it back. I think it would be extremely useful if you could either toggle the angles or separate the angles into different hotkeys like what you did with the hotkey for this mods camera angle. I would really appreciate this! Thanks

**Comment by tacocoma** [comment]
Replacing the default perspective will work just fine for me but I can’t find a config file for shoulder surfing in my minecraft/config folder.

**Comment by Exopandora** [comment]
After you have started the game at least once, with shoulder surfing installed, there should either be `.../.minecraft/config/shouldersurfing.toml` (1.13+) or `.../.minecraft/config/shouldersurfing.cfg` (1.7.10-1.12.2).

**Comment by tacocoma** [comment]
Yea I’m just realizing I don’t have the mod in mods folder or cfg in config folder but the mod works fine. Any ideas? I’m sure its the right instance and folders because if I take something out or add something it changes the modlist in game.

**Comment by Exopandora** [comment]
You probably have a different game/working directory selected.

**Comment by tacocoma** [comment]
You’re right I’m an idiot 😭 I renamed a backup in my launcher but that doesnt change the original filename 🙏 thanks for all your help I got it working how I wanted
