### ISSUE TITLE
Regarding the issue of crosshair placement that could be bad for PVP and Experience

### ISSUE THREAD

**Issue by yuzawijaksana** [Exopandora/ShoulderSurfing#122]
You've already know about the crosshair placement if you use Shoulder Surfing right ?

People who use this in pvp or normal games can affect how they play
![image](https://github.com/Exopandora/ShoulderSurfing/assets/48989307/4c932f13-7f58-40ee-9328-4b3d16f1632f)

for example
"I wanted to open a door, but i needed to go sideways so i can open the door first if i use STATIC/STATIC_WITH_1PP"
![image](https://github.com/Exopandora/ShoulderSurfing/assets/48989307/e8e274c9-f601-4663-9087-5da064e7803e)

Probably a solution for this is just to aim it to the door right ?
![image](https://github.com/Exopandora/ShoulderSurfing/assets/48989307/ebc67ad7-8850-4d92-abd8-fea50945e4ca)

that is true, but i needed to adjust my crosshair & movement at the same time.

my suggestion is, can you add a feature that make an offset for the crosshair similar to dynamic but on static ?
![image](https://github.com/Exopandora/ShoulderSurfing/assets/48989307/555c52e6-ac80-4554-af62-c32e23b57708)

**Comment by Exopandora** [comment]
The problem with automatically switching to the dynamic crosshair when (for example) looking at a door is, that it is not possible to check whether or not a player can interact with a block. It is only possible to start the interaction, but the result is unknown. To implement it nevertheless, it would require a huge list of blocks in the config file a player could interact with. It will also lack support for any other mods.

**Comment by yuzawijaksana** [comment]
Okay, thanks for the explanation. also thanks for other issue you've solved <3

**Comment by NABS2ER** [comment]
Good day. You made a great mod, I didn’t want to create a new topic on this issue, so I’ll write here, okay?!)
Previously, when I rotated the mouse, the body rotated with it, can I activate this function in the settings? Because when retreating back and at the same time attacking from the front, it turns to the side where I press on the keyboard!, that is, the mobs in front of me attack and I hit what’s behind me! this is inconvenient!

**Comment by Exopandora** [comment]
> Good day. You made a great mod, I didn’t want to create a new topic on this issue, so I’ll write here, okay?!) Previously, when I rotated the mouse, the body rotated with it, can I activate this function in the settings? Because when retreating back and at the same time attacking from the front, it turns to the side where I press on the keyboard!, that is, the mobs in front of me attack and I hit what’s behind me! This is inconvenient! it turns out that I'm punching empty air

Set `decoupled_camera` to `false` in the config.

**Comment by Exopandora** [comment]
Closing this issue, as it not possible to implement a scalable solution for the problem.
