### ISSUE TITLE
Use YACL instead of Forge Config API port

### ISSUE THREAD

**Issue by RaptaG** [Exopandora/ShoulderSurfing#123]
**Describe your feature**
[YACL (Yet Another Config Lib)](https://github.com/isXander/YetAnotherConfigLib) is a simple yet powerful config library for both Forge and Fabric, and it would allow for consistency across versions and loaders. It's used by a lot of mods and it is actively maintained. I believe it's worth considering it.

**Comment by Exopandora** [comment]
Thanks for the suggestion. For the time being, SSR will rely on the forge config system, as there would be no benefit in a change, other than additional work.

**Comment by RaptaG** [comment]
@Exopandora could you consider it in the future? It is an easy to use API and using another mod loader's config API in Fabric is a workaround to achieve a cross-compatible config system (which can be done with YACL).

**Comment by Exopandora** [comment]
I will consider it when necessary, thanks!
