### ISSUE TITLE
[FEATURE] [1.19.2] About adding rotation function

### ISSUE THREAD

**Issue by fenlincao** [Exopandora/ShoulderSurfing#124]
First of all, I think it's great, it adds a better third-person view, so the player has more options -- not necessarily in the first person,But I think it still needs to be improved, if you can add the camera rotation function, it will bring a better third-person experience,can make MC truly become a third person game.Thanks!

**Comment by Exopandora** [comment]
Thank you for the suggestion! Do you mean a fixed rotation that is always applied to the view or do you mean a free camera rotation, such that you can spin the camera around the player, without modifying its view vector? If you mean the latter, you can simply install [Better Third Person](https://www.curseforge.com/minecraft/mc-mods/better-third-person) alongside Shoulder Surfing.

**Comment by fenlincao** [comment]
my mean is  a fixed rotation that is always applied to the view,Because I checked a few third person games and found that they all have a fixed rotation, as shown in the photo below

![1](https://github.com/Exopandora/ShoulderSurfing/assets/123194839/dd07c019-da12-4a0b-8b94-031c032309b8)
![2](https://github.com/Exopandora/ShoulderSurfing/assets/123194839/3161ff7e-6706-42c4-9f7a-25bf0257b955)
Below is a picture of MC's Shoulder Surfing


![3](https://github.com/Exopandora/ShoulderSurfing/assets/123194839/afc323b1-9be8-4033-8990-0cc191f05963)

In my personal opinion, the difference between them is only a fixed rotation, with rotation, you can really achieve the effect of third person, MC can really become a third person game
The above is just my personal opinion, not necessarily correct, for reference only,Finally, thank you again!

**Comment by Exopandora** [comment]
I played around with a fixed rotation view and it feels very odd to have the camera at an angle, as you are constantly moving sideways. 

To comment on your images:
1. This can be achieved using Better Third Person to decouple the player rotation from the view rotation. Judging some gameplay footage of the Witcher 3, this is exactly how it works. There is no permanent rototation on the camera. Instead, the rotation of the player model lags behind the camera view.
2. The player is actually looking in line with the camera here. Just the stance has the player models legs at an angle.

I recommend checking out Better Third Person. We can also discuss this topic further, but i don't think it leads to a good user experience.

**Comment by fenlincao** [comment]
I agree with you. I made an error of judgment earlier, and I am deeply sorry。
Also, if I want to adjust the Angle of the legs of the player model by modifying the stance, I want to know if there are any mods I can use because I can't make mods.
Thanks!

**Comment by Exopandora** [comment]
> I agree with you. I made an error of judgment earlier, and I am deeply sorry.

No worries!

> Also, if I want to adjust the Angle of the legs of the player model by modifying the stance, I want to know if there are any mods I can use because I can't make mods.

Unfortunately, I don't know of any. But maybe some enhanced animation mod has what you want.
