### ISSUE TITLE
[Mod Conflict] [1.18.2] keepCameraOutOfHead conflict with the combat mode of the Epic Fight

### ISSUE THREAD

**Issue by Sokusha** [Exopandora/ShoulderSurfing#125]
### Description

When switching to the battle mode of the Epic Fight mod, the player's entity cannot fade out when the camera is close to the player, the camera will enters the player's head. 
By the way, 2.3.0 does not have this issues and the normal 3rd works fine.

### Steps to Reproduce

1.Go to a narrow space, the keepCameraOutOfHead is works fine.
2.Switch to the combat mode of the Epic Fight mod, player's entity cannot fade out

### Expected Behavior

Player's entity cannot fade out

### Game Logs

no logs

### Other Mods

Epic Fight

### Additional Information

The issue occurs in 2.3.2 and 2.4.0, 2.3.0 has no conflict.

**Comment by Exopandora** [comment]
Thanks for the report! For me it works without issue. What you can do to further diagnose the issue:
1. Double check your settings for SSR to ensure `keepCameraOutOfHead` is enabled
2. Try testing with just SSR and Epic Fight Mod installed, as the issue may be caused by yet another mod.

Tested with Forge 1.18.2-40.2.9, SSR 2.4.1 and Epic Fight Mod 18.3.7.

**Comment by Sokusha** [comment]
> Thanks for the report! For me it works without issue. What you can do to further diagnose the issue:
> 
> 1. Double check your settings for SSR to ensure `keepCameraOutOfHead` is enabled
> 2. Try testing with just SSR and Epic Fight Mod installed, as the issue may be caused by yet another mod.
> 
> Tested with Forge 1.18.2-40.2.9, SSR 2.4.1 and Epic Fight Mod 18.3.7.

I've tried, it still happened:(
I delete the whole config folder, defaultconfig folder and mods folder, only get SSR 2.4.1 and Epic Fight Mod 18.3.7 installed, enter game and dig a hole immediatly, combat mode camera still insider player's head
and then i reinstall the whole game ,install Forge 40.2.9, Epic Fight 18.3.7 and SSR 2.4.1 in sequence, but it's no help

**Comment by Exopandora** [comment]
Am i doing something wrong with my testing?

https://github.com/Exopandora/ShoulderSurfing/assets/18708736/a3cab304-8eb6-471f-a9b5-28cd33d51d51

**Comment by Sokusha** [comment]
> Am i doing something wrong with my testing?
> 
>  2023-07-11.16-38-25.mp4

That's what I did, it's so wired :O 

https://github.com/Exopandora/ShoulderSurfing/assets/38533468/097065cd-f545-4b85-a71d-0f51e4e4531b

**Comment by Exopandora** [comment]
I get what you mean now, but i am still unable to reproduce your issue.
1. Are you sure there are no other mods installed?
2. Are you sure that your configs (SSR and Epic Fight Mod) are default?
3. What is your screen resolution?

Maybe i am still doing something wrong, This is what i do:
1. Install Epic Fight Mod (default configuration)
2. Install SSR (default configuration)
3. Press "R" (default keybinding) ingame to switch to combat mode as seen in the previous video

**Comment by Sokusha** [comment]
Yes, my path is:

1. Install a new game
2. Install Forge
3. Install Epic Fight Mod 
4. Install SSR
5. Enter game and then find the issue

all configuration files is stay default.
it is so weird, but at least the 2.3.0 is working fine

**Comment by Exopandora** [comment]
Weird, I did the same. Unfortunately, I am not able to fix this without being able to reproduce the issue. :/

**Comment by Blues7a** [comment]
Exact same issue

**Comment by Exopandora** [comment]
I was finally able to reproduce the bug and issued a fix.
