### ISSUE TITLE
[BUG] [1.20.1] Issue with crosshair when attacking small creatures

### ISSUE THREAD

**Issue by Neguillarro** [Exopandora/ShoulderSurfing#126]
### Description

First of all, I want to thank the person who created this mod, because it is one of my favorite mods.

But I'm having a very annoying problem with the crosshair. I play with the shoulder surfing camera and the crosshair in static mode because I don't like it to move on its own. The default camera was too close to the character, so using the directional buttons I moved it away, and this is where the problem comes from. Even though my character is attached to a creature and the crosshair is touching it, when I attack small creatures like spiders, turtles, or rabbits, the crosshair doesn't detect the creature, so the hit goes right through it and hits directly on the floor block you are stepping on. With large creatures like skeletons or zombies this only happens if I attack their legs, but if I attack them from the middle of their body up there is no problem.

I like the mod a lot and would appreciate it if you would fix this.

### Steps to Reproduce

1. Login in to game
2. I press v to put the camera in shoulder surfing mode
3. I attack a small creature
4. Error, the attack passes through the creature, hitting the block below it

### Expected Behavior

When attacking the blow deals damage to the creature

### Game Logs

https://gist.github.com/Neguillarro/3e9f347a864a696f790aa1f6f4225f02

**Comment by Exopandora** [comment]
Thanks for the report, can you also upload your config file for shoulder surfing (`config\shouldersurfing.toml`)? Does this also happen without any other mods installed?

**Comment by Neguillarro** [comment]
It happens all the time, with other mods and without them. Right now the only mod I have in the folder is this one.

https://gist.github.com/Neguillarro/2a325992bdc082e637f9dea9103ab5e9

**Comment by Neguillarro** [comment]
I forgot to mention that in the last games I changed the crosshair to adaptive mode, but the same thing happens as in static.

**Comment by Exopandora** [comment]
Thanks! I will look into it.

**Comment by Exopandora** [comment]
The issue has been fixed, and a new version will soon be available to download. Thanks again for the report.
