### ISSUE TITLE
[Suggestion] Replace `ClipContext.Block.COLLIDER` with `ClipContext.Block.VISUAL`

### ISSUE THREAD

**Issue by 70CentsApple** [Exopandora/ShoulderSurfing#128]
Currently, the mod also collides with perspectives when encountering blocks such as glass, while in newer versions of Minecraft, the perspective does not collide with blocks such as glass.

The way to fix this is really simple, replace `ClipContext.Block.COLLIDER` with `ClipContext.Block.VISUAL` [here](https://github.com/Exopandora/ShoulderSurfing/blob/master/common/src/main/java/com/teamderpy/shouldersurfing/client/ShoulderRenderer.java#L92).
https://github.com/Exopandora/ShoulderSurfing/blob/93fec6f503487e3ed1dd87ebb0d6879bddefd567/common/src/main/java/com/teamderpy/shouldersurfing/client/ShoulderRenderer.java#L92

The definition of and difference between `COLLIDER` and `VISUAL` are shown below:
_1.20.1: net.minecraft.world.level.ClipContext_
![image](https://github.com/Exopandora/ShoulderSurfing/assets/63957117/3dd9d41e-5e8b-4d3b-8582-50adc89dd737)

This little fix might not bring significant changes, but it fixes mods that modify camera collisions of blocks by modifying the `BlockBehaviour.BlockStateBase::getVisualShape` method (such as mine, [Modify Camera Collision](https://modrinth.com/mod/modify-camera-collision)).

**I could make a PR for this issue, but if there's any reason why I shouldn't, please let me know.**

**Comment by Exopandora** [comment]
Thanks for the pointer! Feel free to make a PR.
