### ISSUE TITLE
cant get it to work on a modpack

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Exopandora/ShoulderSurfing#13]
no error log, nothing telling me why, i put the jar in the mods folder, and it does not work.  i empty the mod list of all other mods, it still dont work. 
MC version: 1.12.2
forge version: 14.23.5.2831

**Comment by Exopandora** [comment]
Could you please upload the logs anyways ?

**Comment by Exopandora** [comment]
ShoulderSurfing 1.12.2-1.15.1 works as intended with Forge 14.23.5.2838
