### ISSUE TITLE
[BUG] [FEATURE] [1.19.2] Shoulder Surfing re-enable front view tpp

### ISSUE THREAD

**Issue by D3CXII** [Exopandora/ShoulderSurfing#135]
### Description

There's an option in the Better Third Person mod that remove the front view 3p mode entirely. Now, when using BTP with Shoulder Surfing it re-enable the front view tpp, can you make that this mod doesn't override BTP config or add removing front view as an option.

### Steps to Reproduce

1. Install Better Third Person and Shoulder Surfing together
2. Toggle "Skip Third Person Front VIew"
3. Switch perspective

### Expected Behavior

Pressing F5 once take you to the back view tpp/shoulder surfing view
Pressing F5 again take you back to fpp

### Screenshots

https://github.com/Exopandora/ShoulderSurfing/assets/148952127/45698fe2-eb00-4c52-aad8-dc5100d08c8c

### Game Logs

<script src="https://gist.github.com/D3CXII/c77e62997e7379150dd07906068663a2.js"></script>

### Other Mods

Better Third Person

**Comment by Exopandora** [comment]
Thanks for the report! SSR has the optional keybind "Toggle perspective", which switches perspective between first person and shoulder surfing. You can use this key instead of "F5". However, i will fix this in a next release.
