### ISSUE TITLE
[BUG] [1.18.2] setCameraType redirect conflict with SecurityCraft

### ISSUE THREAD

**Issue by HydraSquid** [Exopandora/ShoulderSurfing#139]
### Description

After latest update, the game hangs on startup on this log line:
`@Redirect conflict. Skipping shouldersurfing.mixins.json:MixinMinecraft->@Redirect::setCameraType(Lnet/minecraft/client/Options;Lnet/minecraft/client/CameraType;)V with priority 1000, already redirected by securitycraft.mixins.json:camera.MinecraftMixin->@Redirect::securitycraft$preventCameraSwitching(Lnet/minecraft/client/Options;Lnet/minecraft/client/CameraType;)V with priority 1100`

### Steps to Reproduce

1. Install SecurityCraft v1.9.8
2. Install ShoulderSurfing v2.7
3. Attempt to start game
4. Notice process hangs or crashes with no crash report

### Expected Behavior

Game starts normally

### Game Logs

https://gist.github.com/HydraSquid/74705262d6aa1f80b5d4b9fdbfdc60c0

### Other Mods

SecurityCraft v1.9.8

**Comment by Exopandora** [comment]
Thanks for the report! It should be fixed in 2.8.
