### ISSUE TITLE
cant get it to work no matter what

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Exopandora/ShoulderSurfing#14]
same as my previously closed issue, sorry i didnt get notified you had replied.

same everything as before but now, tested on latest forge: 14.23.5.2838 

https://cdn.discordapp.com/attachments/546964295360053248/585517354914676737/unknown.png
https://cdn.discordapp.com/attachments/546964295360053248/585518991712452631/unknown.png
my trying to send you the latest.log
https://cdn.discordapp.com/attachments/546964295360053248/585519793508188170/unknown.png
https://cdn.discordapp.com/attachments/546964295360053248/585519953361240093/unknown.png
if you know of a way for me to send you a 1.8mb .log file, you lemme know and i'll get on it.
~~edit: decided to just upload through google drive, the debug.log and the latest.log
https://drive.google.com/file/d/1c8ikB9vwagpAD6Hstk2pJVC10RapQ8ju/view?usp=sharing
https://drive.google.com/file/d/1AIQExfKzOtQR8dzjksQ_igZZdjtS4rLN/view?usp=sharing
also a pastebin of the modlist in use
https://pastebin.com/rhK7xTqP

**Comment by Exopandora** [comment]
It says "Loaded 9 code injections, ShoulderSurfing good to go". Did you press i, j, k ,l to configure the perspective ? Are other mods using the same keys ?

**Comment by Exopandora** [comment]
It might also be an incompatibility issue with another mod

**Comment by GeminiMarshdevil** [comment]
ahah, ok lemme try that. does shoulder surfing have a dedicated category under config keybinds?

**Comment by Exopandora** [comment]
They are registered under misc

**Comment by GeminiMarshdevil** [comment]
yea i got nuffen bud,  i, j, k are free, L is for achievements (defacto across all modpacks) but even so,
custom rebinding of "swap shoulder" and playing with any of the "camera" buttens dont do much
![image](https://user-images.githubusercontent.com/35816347/58902720-abcaeb00-86d1-11e9-87a0-17c6a052d19a.png)

**Comment by Exopandora** [comment]
Try setting shoulder_rotation_offset to -20 in the config file and see if it changes the perspective ingame

**Comment by GeminiMarshdevil** [comment]
maybe im blind, and my search tool sucks but what?
https://pastebin.com/kc3zA969

**Comment by Exopandora** [comment]
Line 35 "Rotation Offset" sry it's the old config name

**Comment by GeminiMarshdevil** [comment]
Oppa! crash report! 
https://pastebin.com/hBdD4fuF

**Comment by Exopandora** [comment]
Looking at the stacktrace its more likely that biomesoplenty crashed the game than shouldersurfing. (It was related to worldgen and was called from biomesoplenty). Please try launching the game again

**Comment by GeminiMarshdevil** [comment]
yep, the gods did hear your order and arranged it so the game is now more stable because you dubbed it so (not joking, legit)

**Comment by Exopandora** [comment]
Its all in the config

**Comment by Exopandora** [comment]
Normally you would use I, J, K. L. You can configure the offsets in the config tho

**Comment by GeminiMarshdevil** [comment]
this specific section makes me think that my players will be able to adjust their camera ingame
![image](https://user-images.githubusercontent.com/35816347/58906293-9659bf00-86d9-11e9-9b34-7c2d666ba02b.png)

also i cant find anything in the config about customizing IJKL or any keybinds?

**Comment by Exopandora** [comment]
You configure the keybinds ingame in the menu:

> 
> 
> yea i got nuffen bud, i, j, k are free, L is for achievements (defacto across all modpacks) but even so,
> custom rebinding of "swap shoulder" and playing with any of the "camera" buttens dont do much
> ![image](https://user-images.githubusercontent.com/35816347/58902720-abcaeb00-86d1-11e9-87a0-17c6a052d19a.png)

**Comment by GeminiMarshdevil** [comment]
Got it ^^ ty.

**Comment by Exopandora** [comment]
So is this issue resolved now ?

**Comment by GeminiMarshdevil** [comment]
i believe so,  its just a default config file that sets your camera in third person to have no offset, so it doesnt seem like the mod works at first, and then the options keybinds not being preconfigured or by default occupying other mods keybinds XD

**Comment by Exopandora** [comment]
The keybinds will be configured by the mod (I guess you installed another mod that unbinds all mod keys so they dont interfer). Just provide an override config file for shouldersurfing upon distribution

**Comment by Exopandora** [comment]
I just noticed that i changed the default keys from I, j, k, l to the arrow keys
