### ISSUE TITLE
[BUG] [1.18.2] Incompatibility with Nimble

### ISSUE THREAD

**Issue by Mystifyed** [Exopandora/ShoulderSurfing#141]
### Description

Smooth camera transition that Nimble adds is broken when SSR is installed.

### Steps to Reproduce

1. Install Nimble with SSR
2. Smooth camera transition doesn't work properly 

### Expected Behavior

I expected the smooth camera transition to work properly

### Game Logs

N/A

**Comment by Exopandora** [comment]
This needs support from the authors of Nimble.
