### ISSUE TITLE
[FEATURE] Request adaptation to the Timeless and Classics Guns mod

### ISSUE THREAD

**Issue by wyh0106** [Exopandora/ShoulderSurfing#143]
In Timeless and Classics Guns mod, the guns aiming in over-the-shoulder view automatically switches back to first person, and the crosshair corresponds to the actual impact point of the firearm in over-the-shoulder view (which is not corresponding).

**Comment by Exopandora** [comment]
Thanks for the suggestion. This is a feature cannot be implemented as the player is never looking at that position with his head in the first place. However, you could add all weapons of Timeless and Classics Guns to `adaptive_crosshair_items` within Shoulder Surfings config file (`.minecraft\config\shouldersurfing.toml`). This would enable the dynamic crosshair or switch you to first person (depending on `crosshair_type`) when a weapon of Timeless and Classics Guns is held.
