### ISSUE TITLE
[FEATURE] Position dynamic crosshair at point of interaction

### ISSUE THREAD

**Issue by PencilVoid** [Exopandora/ShoulderSurfing#144]
Currently, when the crosshair is set to "dynamic" it positions itself somewhere between the player's head and where the player is looking. This makes it difficult to do things that require some degree of precision, such as pressing buttons or attacking mobs. Positioning the crosshair at the end of the raycast, i.e. where the player is looking, would help to alleviate this.

**Comment by Exopandora** [comment]
I think what you want is to limit the raytrace distance to the players reach. This can be done (approximately) by setting `custom_raytrace_distance` to `5.0`.

**Comment by PencilVoid** [comment]
The player reach varies between game modes. According to the Minecraft Wiki, reach is 5.2 blocks in Creative mode and 4.5 blocks otherwise. It would be nice if the mod could handle this automatically.

**Comment by Exopandora** [comment]
I don't know why this didn't come to my mind earlier, but you can achieve exactly that by setting `use_custom_raytrace_distance` to `false`.
