### ISSUE TITLE
[BUG] [1.19.2] Incompatible with "Mana and Artifice Reloaded" 

### ISSUE THREAD

**Issue by HendersonT** [Exopandora/ShoulderSurfing#145]
### Description

If both Mana and Artifice and Shoulder surfing reloaded are loaded, the client will crash if the camera gets close to a block behind the player, triggering a "Pose stack not empty" crash. 

### Steps to Reproduce

1. Load Minecraft with only Mana and Artifice, Shoulder SUrfing Reloaded, and their dependencies. 
2. Go into third person
3. Get close to a block behind the player head, e.g. intersect the camera with a tree.
4. Game freezes and crashes.

### Expected Behavior

The game should not crash, the camera should shift to a first person perspective.

### Game Logs

https://pastebin.com/YiLWgzgQ

### Other Mods

Mana and Artifice

### Additional Information

If Either mod is removed, the issue does not occur.

**Comment by HendersonT** [comment]
Reported to Mana and Artifice as well.

**Comment by Exopandora** [comment]
Thanks for the report. As a temporary workaround, you can set `keep_camera_out_of_head_distance_multiplier` to `0.0` to avoid the crash.
