### ISSUE TITLE
[BUG] [1.20.4] Forge Config API Port isn't working or broken

### ISSUE THREAD

**Issue by Tapacywka** [Exopandora/ShoulderSurfing#147]
### Description

There is no button to configure the mod via ModMenu. I'm using the latest version of Shoulder Surfing Reloaded and Forge Config API Port.

### Steps to Reproduce

Install Fabric API, Forge Config API Port and Shoulder Surfing Reloaded on Fabric 1.20.4; start the game; goto Mods.

### Expected Behavior

There should be a button to configure the configuration.

### Game Logs

none

### Additional Information

If possible, transfer configs from Forge Config API Port to Cloth Config API or YACL.

**Comment by Exopandora** [comment]
This is a limitation of [Forge Config API Port](https://github.com/Fuzss/forgeconfigapiport) and there are not plans to replace the current implementation. In earlier Minecraft versions, [Configured ](https://www.curseforge.com/minecraft/mc-mods/configured) could be used to get an ingame GUI for config files.
