### ISSUE TITLE
Functionality with other mods

### ISSUE THREAD

**Issue by NABS2ER** [Exopandora/ShoulderSurfing#148]
Hello code creators!) 
Please help, my build includes several weapon mods and when shooting from them your aim is not accurate. If, when shooting from a bow, your sight moves to where the arrow is flying, then, alas, there is no such thing here! (These are the mods with which difficulties arise: MrCrayfish's Gun Mod;, Stabx Modern Guns;, Alliance of Valiant Arms Guns;, Point Blank! There are a few more, but they are not very significant. It would be very cool if the sight worked correctly with these mods! Thank you for your attention

**Comment by Exopandora** [comment]
Please see #143

**Comment by NABS2ER** [comment]
Thank you, I read this news but didn’t quite understand what and how! Could you use an example of one or more types of weapons to explain how to do this? I don't think I can do this on my own without your help and support. (V. Mine. 1.20.1)

**Comment by NABS2ER** [comment]
By the way, while I was playing now, in some moments it was somewhat inconvenient, for example, in cramped rooms, closets and similar rooms, the sight was behind the head, but it was unclear where he was looking, it would be great if at this moment the character himself and his clothes were equipment and tools in the hands became translucent, like in most RPG games. Otherwise, it’s inconvenient to open the drawers and even look around.
![2024-01-29_22 25 20](https://github.com/Exopandora/ShoulderSurfing/assets/141981213/5b9d4d3e-1e62-4c7f-8e44-6b07037b6e28)
![2024-01-29_22 24 45](https://github.com/Exopandora/ShoulderSurfing/assets/141981213/4867c82e-1363-4f2a-aa4b-70fa7f0d60f1)

**Comment by Exopandora** [comment]
1. Find out the id of the item that should have a "dynamic" crosshair
   1. Press `F3`+`H` ingame to enable advanced tooltips
   2. Hover over the item in the inventory
   3. At the bottom of the tooltip, it should say the item id. If you are hovering over a stack of stone for example, it should say `minecraft:stone`
2. Goto `../.minecraft/config`
3. Open `shouldersurfing.toml` with a text editor
4. Find `adaptive_crosshair_items`. By default it should look as follows:
   ```toml
   adaptive_crosshair_items = ["minecraft:snowball", "minecraft:egg", "minecraft:experience_bottle", "minecraft:ender_pearl", "minecraft:splash_potion", "minecraft:fishing_rod", "minecraft:lingering_potion"]
   ```
5. Now add the the item id to the array. As an example, i will add `minecraft:stone`:
   ```toml
   adaptive_crosshair_items = ["minecraft:stone", "minecraft:snowball", "minecraft:egg", "minecraft:experience_bottle", "minecraft:ender_pearl", "minecraft:splash_potion", "minecraft:fishing_rod", "minecraft:lingering_potion"]
   ```
6. Save the file and start minecraft
7. Whenever you are holding stone now, it will automatically switch to the dynamic crosshair
8. You can repeat the steps for every item

**Comment by NABS2ER** [comment]
> 1. Find out the id of the item that should have a "dynamic" crosshair
>    
>    1. Press `F3`+`H` ingame to enable advanced tooltips
>    2. Hover over the item in the inventory
>    3. At the bottom of the tooltip, it should say the item id. If you are hovering over a stack of stone for example, it should say `minecraft:stone`
> 2. Goto `../.minecraft/config`
> 3. Open `shouldersurfing.toml` with a text editor
> 4. Find `adaptive_crosshair_items`. By default it should look as follows:
>    ```toml
>    adaptive_crosshair_items = ["minecraft:snowball", "minecraft:egg", "minecraft:experience_bottle", "minecraft:ender_pearl", "minecraft:splash_potion", "minecraft:fishing_rod", "minecraft:lingering_potion"]
>    ```
> 5. Now add the the item id to the array. As an example, i will add `minecraft:stone`:
>    ```toml
>    adaptive_crosshair_items = ["minecraft:stone", "minecraft:snowball", "minecraft:egg", "minecraft:experience_bottle", "minecraft:ender_pearl", "minecraft:splash_potion", "minecraft:fishing_rod", "minecraft:lingering_potion"]
>    ```
> 6. Save the file and start minecraft
> 7. Whenever you are holding stone now, it will automatically switch to the dynamic crosshair
> 8. You can repeat the steps for every item

Thank you very much for taking the time and explaining everything in detail, I did everything as you said, and voila, everything really worked, I’m so glad)) You are just super. thank you, thank you, thank you!)

**Comment by NABS2ER** [comment]
But the problem with narrow rooms is very annoying; is it possible to make it so that every time the camera touches the wall, the hero and everything he is wearing become translucent?

**Comment by Exopandora** [comment]
> But the problem with narrow rooms is very annoying; is it possible to make it so that every time the camera touches the wall, the hero and everything he is wearing become translucent?

I had this idea a while ago, but did not proceed with the implementation, as is a bit tricky. I also fear that it will break compatibility with other mods.

**Comment by NABS2ER** [comment]
but just imagine, if it works, it will be simply incredible and convenient, maybe it’s worth at least trying and releasing a test version of the mod, and also using the config to add those elements from the mod that should also be translucent. Without exaggeration, I have 505 mods in minecraft, and every time I add something new. I could test your mod with other mods. Great idea.)
Tell me, is the crosshair in your mod a little smaller and more convenient? After one of the mods I added, I got a large standard crosshair, this mod didn’t suit me and I deleted it, and I even reinstalled some mods again, clearing the config folder, but the crosshair did not change! Tell me, do you happen to know how to manually change the size of the crosshair or simply return it to its previous appearance?

**Comment by NABS2ER** [comment]
1. Does not work with a standard telescope, it is very inconvenient to switch to first-person view to look through it

2. The target is a block that you cannot aim at, the crosshair slides off it. 
The sight is located exactly in the middle above the character's head.
And in connection with this, when you begin to move the sight under you, at some point it jumps over a whole block under your feet. More than once I’ve been faced with the fact that I need to kill a skeleton, I draw my bow but I can’t aim, it misses the position I need! Or during construction I can’t get to the block I need! 

![2024-02-03_10 20 11](https://github.com/Exopandora/ShoulderSurfing/assets/141981213/29f158e6-c1e8-4d5d-9ed5-eda8af51e3fe)

![2024-02-03_10 20 07](https://github.com/Exopandora/ShoulderSurfing/assets/141981213/0e1601dc-0964-4224-94af-83d03881f750)

**Comment by Exopandora** [comment]
> 1. Does not work with a standard telescope, it is very inconvenient to switch to first-person view to look through it
> 
>     2. The target is a block that you cannot aim at, the crosshair slides off it.
>        The sight is located exactly in the middle above the character's head.
>        And in connection with this, when you begin to move the sight under you, at some point it jumps over a whole block under your feet. More than once I’ve been faced with the fact that I need to kill a skeleton, I draw my bow but I can’t aim, it misses the position I need! Or during construction I can’t get to the block I need!
> 
> 
> ![2024-02-03_10 20 11](https://private-user-images.githubusercontent.com/141981213/301999765-29f158e6-c1e8-4d5d-9ed5-eda8af51e3fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTk2MjQsIm5iZiI6MTcwNjk1OTMyNCwicGF0aCI6Ii8xNDE5ODEyMTMvMzAxOTk5NzY1LTI5ZjE1OGU2LWMxZTgtNGQ1ZC05ZWQ1LWVkYThhZjUxZTNmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMTIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2Q0OWM4OGVmOTMwZjQwYzAxZTY2MDE0N2JiMTk1MWNjODVhYzgwODBmNDFjZDY0YjZhNmUxYzUyNzBkYmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lil4ribE5Rv2m0CduvXpbmeuecW6NFYu6xR-5mGW2Xo)
> 
> ![2024-02-03_10 20 07](https://private-user-images.githubusercontent.com/141981213/301999756-0e1601dc-0964-4224-94af-83d03881f750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTk2MjQsIm5iZiI6MTcwNjk1OTMyNCwicGF0aCI6Ii8xNDE5ODEyMTMvMzAxOTk5NzU2LTBlMTYwMWRjLTA5NjQtNDIyNC05NGFmLTgzZDAzODgxZjc1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMTIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTQ1YmEyYWNlOWFhYTIzMTg5ZDdjZmIxZDk0MDBkYzQzZjVlZTlhZWE3OGJhZGY0NDMzNTMxMmNlZTU0YjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gY4_odo2yNEDb--qyNtpfM4vGUj5db5fI5nufpDVbNI)

Please file different issues/bugs in separate github issues.

**Comment by NABS2ER** [comment]
> > 1. Does not work with a standard telescope, it is very inconvenient to switch to first-person view to look through it
> >    
> >    2. The target is a block that you cannot aim at, the crosshair slides off it.
> >       The sight is located exactly in the middle above the character's head.
> >       And in connection with this, when you begin to move the sight under you, at some point it jumps over a whole block under your feet. More than once I’ve been faced with the fact that I need to kill a skeleton, I draw my bow but I can’t aim, it misses the position I need! Or during construction I can’t get to the block I need!
> > 
> > ![2024-02-03_10 20 11](https://private-user-images.githubusercontent.com/141981213/301999765-29f158e6-c1e8-4d5d-9ed5-eda8af51e3fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTk2MjQsIm5iZiI6MTcwNjk1OTMyNCwicGF0aCI6Ii8xNDE5ODEyMTMvMzAxOTk5NzY1LTI5ZjE1OGU2LWMxZTgtNGQ1ZC05ZWQ1LWVkYThhZjUxZTNmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMTIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2Q0OWM4OGVmOTMwZjQwYzAxZTY2MDE0N2JiMTk1MWNjODVhYzgwODBmNDFjZDY0YjZhNmUxYzUyNzBkYmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lil4ribE5Rv2m0CduvXpbmeuecW6NFYu6xR-5mGW2Xo)
> > ![2024-02-03_10 20 07](https://private-user-images.githubusercontent.com/141981213/301999756-0e1601dc-0964-4224-94af-83d03881f750.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NTk2MjQsIm5iZiI6MTcwNjk1OTMyNCwicGF0aCI6Ii8xNDE5ODEyMTMvMzAxOTk5NzU2LTBlMTYwMWRjLTA5NjQtNDIyNC05NGFmLTgzZDAzODgxZjc1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwM1QxMTIyMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTQ1YmEyYWNlOWFhYTIzMTg5ZDdjZmIxZDk0MDBkYzQzZjVlZTlhZWE3OGJhZGY0NDMzNTMxMmNlZTU0YjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gY4_odo2yNEDb--qyNtpfM4vGUj5db5fI5nufpDVbNI)
> 
> Please file different issues/bugs in separate github issues.

I apologize, I thought it would be more appropriate to write here, since the problem is almost the same. Should I create a topic and copy all this there?

**Comment by Exopandora** [comment]
Please file a different issue for topic 1. For topic 2. there is a config option called `center_camera_when_looking_down_angle` in `shouldersurfing.toml`. If you set it to a lower value, the camera will center later. If you set it to `0` it will not center at all when you look down.

**Comment by NABS2ER** [comment]
> Please file a different issue for topic 1. For topic 2. there is a config option called `center_camera_when_looking_down_angle` in `shouldersurfing.toml`. If you set it to a lower value, the camera will center later. If you set it to `0` it will not center at all when you look down.

I tried changing the value as you said, I tried a bunch of different options, but I didn’t see much of a difference! But!
Of course, it is very strange that not all objects have a crosshair like a bow when aiming, because I just tried to add other objects to this file, as you said earlier, namely a sword and a building block, and it turned out perfect for me. Tell me, can I do with one command everything that is in Minecraft, what I just did with individual items?

**Comment by Exopandora** [comment]
If you want to use the dynamic crosshair (moving crosshair) for all items, set `crosshair_type` to `DYNAMIC`.

**Comment by NABS2ER** [comment]
> By the way, while I was playing now, in some moments it was somewhat inconvenient, for example, in cramped rooms, closets and similar rooms the sight was behind the head, but it was unclear where it was looking, it would be great if at this moment the character himself and his clothes with equipment , became translucent, like in most RPG games. Otherwise, it’s inconvenient to open drawers and even look around. ![2024-01-29_22 25 20](https://private-user-images.githubusercontent.com/141981213/300451150-5b9d4d3e-1e62-4c7f-8e44-6b07037b6e28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjAzMzIsIm5iZiI6MTcxMDA2MDAzMiwicGF0aCI6Ii8xNDE5ODEyMTMvMzAwNDUxMTUwLTViOWQ0ZDNlLTFlNjItNGM3Zi04ZTQ0LTZiMDcwMzdiNmUyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwODQwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmVhNWZhYTMxZmYzZTU2YjkyNTQxMjU1ZDg3NTYyOTBmMzllZDYxNDA1Y2ZmZGM4YzRkMzk5MmY0ZTcyOWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oTIWCmt_M643rC_IWsJIniTIlDxrPd3Szg7UPmL3spM) ![2024-01-29_22 24 45](https://private-user-images.githubusercontent.com/141981213/300451164-4867c82e-1363-4f2a-aa4b-70fa7f0d60f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNjAzMzIsIm5iZiI6MTcxMDA2MDAzMiwicGF0aCI6Ii8xNDE5ODEyMTMvMzAwNDUxMTY0LTQ4NjdjODJlLTEzNjMtNGYyYS1hYTRiLTcwZmE3ZjBkNjBmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQwODQwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQzNjUzN2YzZWQxMjRmNDcxNzU3MjY0YTgxZWNmMDc0MDA0Y2Y1ZTllZDVlODFlYzdlYmU4N2RhMjI5NmI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D_Ow6AKUah4qB55ZRxs5hYUSy28QZNvBXzErcKf6vJM)

I would like to offer one idea, maybe you will still be able to implement this transparency function!
Of course, if you haven’t changed your mind, and simply don’t know how to implement this function, maybe this mod will help you
There is such a mod Better Invisibility.  Here is the link  https://www.curseforge.com/minecraft/mc-mods/better-invisibility
It makes the player and all his equipment invisible, maybe this can somehow be used for our purposes?
Well, it’s natural that this effect would be just a dummy for mobs but real for us

**Comment by Exopandora** [comment]
Transparency manipulation was implemented in the same update (2.9.+) as the spyglass "fix". If it does not work for you, please file a separate issue and isolate the conflicting mod(s).

**Comment by NABS2ER** [comment]
I don’t even know how correctly it works for me, because I don’t know how it should! Well, for example, it’s like mine now, and I don’t know if it should be transparent in this position.
![2024-03-10_20 12 46](https://github.com/Exopandora/ShoulderSurfing/assets/141981213/cfb227a4-d5ca-45ec-b684-75270e3f2ca1)

Well, for example, if you stand close to the wall, it seems to work, but it worked even before the update. So I don't know
![2024-03-10_20 12 59](https://github.com/Exopandora/ShoulderSurfing/assets/141981213/1d78b155-8b10-41f5-bd91-1c666362ba1a)

**Comment by NABS2ER** [comment]
Сan you show how this should work? and if it doesn't work correctly for me, I'll create a new topic and show the problem

**Comment by Exopandora** [comment]
When the crosshair moves behind the player, the player model (and armor), become transparent. Most likely, the mods that you have installed, have custom renderers for armor that do not allow for transparent rendering.

![screenshot.png](https://github.com/Exopandora/ShoulderSurfing/assets/18708736/15ba9f40-9847-4c74-8869-c91959d123e7)

**Comment by Exopandora** [comment]
> **And how do I know which mods conflict?** If there is one at all

You can use [this](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a) method.

**Comment by Exopandora** [comment]
The issue is known to be caused by sodium, oculus and optifine.
