### ISSUE TITLE
[INCREASE] A standard telescope does not work.

### ISSUE THREAD

**Issue by NABS2ER** [Exopandora/ShoulderSurfing#149]
When using a telescope, it is very awkward to switch to first person view to look through it.
It would be great if, when using a telescope, the camera went to it and then returned back

**Comment by NABS2ER** [comment]
It would also be nice if, using the config, you could add items from other mods there, such as weapons, and they would also switch to an enlarged view, and then return back!

**Comment by Exopandora** [comment]
Thanks for the separate report. It will not be possible to simply add a confing option for other mods, since it needs explicit support from them. Even then it might not even be possible, since it needs tight integration with SSR. You might be better off setting `crosshair_type` to `STATIC_WITH_1PP` in the shoulder surfing config and adding the desired weapons manually.

**Comment by NABS2ER** [comment]
> If you want to use the dynamic crosshair (moving crosshair) for all items, set `crosshair_type` to `DYNAMIC`.

If I have already configured crosshair_type dynamic, then what should I do now? Or do I just need a new line in the document with a command like this to add?>   <<STATIC_WITH_1PP_crosshair_items = ["item",  and so on>>
If yes, then explain with an example, like last time, otherwise I don't quite understand

**Comment by Exopandora** [comment]
In `shouldersurfing.toml`, change
```toml
#Crosshair type to use for shoulder surfing.
#Allowed Values: ADAPTIVE, DYNAMIC, STATIC, STATIC_WITH_1PP, DYNAMIC_WITH_1PP
crosshair_type = "ADAPTIVE"
```
to
```toml
#Crosshair type to use for shoulder surfing.
#Allowed Values: ADAPTIVE, DYNAMIC, STATIC, STATIC_WITH_1PP, DYNAMIC_WITH_1PP
crosshair_type = "DYNAMIC"
```

**Comment by NABS2ER** [comment]
Done, what next or is that all? You wrote above about the crosshair_type configuration STATIC_WITH_1PP

**Comment by Exopandora** [comment]
Those are just comments for the user (you), so you know what values other than `ADAPTIVE` and `DYNAMIC` can be used. You can try out the others if you want. Otherwise you are done.

**Comment by NABS2ER** [comment]
What about the telescope zoom?

**Comment by Exopandora** [comment]
I will be there when it's finished, please stop begging.

**Comment by NABS2ER** [comment]
Did you succeed?

**Comment by Exopandora** [comment]
The vanilla spyglass will work in the shoulder surfing perspective in the next update. But first i want to achieve feature parity with older supported versions of minecraft.
