### ISSUE TITLE
[suggestion] dedicated ingame keybind category menu section

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Exopandora/ShoulderSurfing#15]
pretty self explanatory,  turns out allot of confusion can be nullified by having a section in the keybinds segregating shoulder surfing from the other many camera controls other mods have x.x

**Comment by Exopandora** [comment]
Its a good point but i would only do that for the 1.13.2 versions and newer as i do not want to support outdated versions with content updates (just fixes).

**Comment by Exopandora** [comment]
ShoulderSurfing 1.14.2-1.18 and newer will feature a separate category for keybindings
