### ISSUE TITLE
[FEATURE] Camera center offset

### ISSUE THREAD

**Issue by dldev32** [Exopandora/ShoulderSurfing#150]
It would be very convenient if it was possible to shift the center of rotation of the camera, especially when playing with vehicles from Valkyrien Skies.

**Comment by Exopandora** [comment]
Thanks for the suggestion. Changing the rotation center of the camera is out of scope for this mod. Maybe ask the authors of Valkyrien Skies directly if they can adjust the camera position when mounted to a Valkyrien Skies vehicle. Note that Valkyrien Skies is not supported by Shoulder Surfing.
