### ISSUE TITLE
[BUG] [1.20] Crosshair inconsistency with Better Third Person

### ISSUE THREAD

**Issue by rayhanhamada93** [Exopandora/ShoulderSurfing#151]
### Description

Holding loaded crossbow with better third person mod makes the crosshair looks like this:
<img width="897" alt="image" src="https://github.com/Exopandora/ShoulderSurfing/assets/74540871/1cf33651-65b7-41ab-8fe6-56ac4ce06268">

I'm guessing this is due to adaptive crosshair switch the crosshair type to dynamic, while dynamic crosshair shifts the crosshair to the block we targets, while better third person makes you able to target block like this screenshot below:
<img width="960" alt="image" src="https://github.com/Exopandora/ShoulderSurfing/assets/74540871/29acb54e-092e-49d9-9a9b-a7948ecd8b28">

### Steps to Reproduce

-

### Expected Behavior

-Install both better third person and shoudlder surfing.
-Load a crossbow, wait for around 5 seconds, then move your character with either A or D.

### Game Logs

-

**Comment by Exopandora** [comment]
This is how the combination of both mods work. Better Third Person decouples the camera rotation from the player rotation, meaning that the player could look at a block, where the center of your does not look at. The dynamic crosshair of shoulder surfing works in a way, such that it moves the crosshair to the on-screen position, where the ray coming from the players head intersects with a block or entity. In your screenshots, you can see that the crosshair is pointing exactly at the position where the player is looking at.

**Comment by rayhanhamada93** [comment]
Yes I can see that, but the problem is it's pretty hard to aim with loaded crossbow since the crosshair is just flying around the screen, even though the arrow will shoot to the center of the screen and not from where the player is looking (because Better Third Person will make the player perspective back to the center on right/left click).

With that being said, is there a way to exclude crossbow from triggering the dynamic crosshair when using adaptive crosshair? Since we can add an item to trigger dynamic crosshair but not the other way around. Ty in advance! ^^

**Comment by Exopandora** [comment]
The trigger for the dynamic crosshair is based on item tags. You will be able to configure them in the next version of SSR.

**Comment by rayhanhamada93** [comment]
that would be awesome, tysm! ^^
