### ISSUE TITLE
Update 2.9 of ShoulderSurfing was not out on CurseForge and Modrinth

### ISSUE THREAD

**Issue by Titoo8899** [Exopandora/ShoulderSurfing#152]
### Description

I have yesterday see a new Update of CurseForge and Modrinth of your mod ShoulderSurfing but the sites have no new Files of the new version. Is it a bug or why was yesterday no update out?

### Steps to Reproduce

Go to Modrinth or Curseforge and go to your mod

### Expected Behavior

I have hope the Modfiles was normal load on the sites on Modrinth and CurseForge but the Files was not show on the sites.

Then I shop the last update for 1 Day but yesterday was not new files on the sites.

### Screenshots

![FireShot Capture 001 - Shoulder Surfing Reloaded - Minecraft Mod - modrinth com](https://github.com/Exopandora/ShoulderSurfing/assets/42325138/65e9cef7-f2b2-4699-a04a-6abe0880ed92)

### Game Logs

have I now is now direct bug it is a Download Problem

**Comment by Exopandora** [comment]
I retracted the update, as it had some bugs. A new version without those bugs will be available later this week (maybe even today).
