### ISSUE TITLE
[BUG] [1.20.4] Stuck on Red Mojang Loading Screen

### ISSUE THREAD

**Issue by Magalia1020** [Exopandora/ShoulderSurfing#155]
### Description

When ShoulderSurfing was installed, my Minecraft stuck on Mojang Screen when I started it. As soon as I uninstalled this mod, the problem fixed. I'm pretty sure it was this mod that caused the problem because I uninstalled my mods one by one to check it.

### Steps to Reproduce

1. Download the mod
2. Put it in the mod folder
3. Start the game
4. Stuck on Mojang Loading Screen

### Expected Behavior

When I entered the game, the Red Mojang Screen loading bar proceeded as usual, but when it was about to complete the loading, it got stuck without the main menu showing up, but main menu music still started playing.

### Game Logs

I was unable to get the log since I couldn't enter the main menu in the first place.

**Comment by Exopandora** [comment]
Thanks for the report. I have no issues launching the game on my side.

Forge Setup:
- Forge 49.0.30
- SSR 2.9.1-1.20.4

Fabric Setup:
- Fabric Loader 0.15.7-1.20.4
- Fabric API 0.96.4+1.20.4
- Forge Config API Port 20.4.3-1.20.4-Fabric
- SSR 2.9.1-1.20.4

Please provide the game logs in order for me to further investigate the issue.

**Comment by Exopandora** [comment]
This issue may be related to #157. Let me know if you are still having issues in SSR 2.9.4+.

**Comment by Exopandora** [comment]
Closing this for now. If you are still having issues, feel free to reopen this issue.
