### ISSUE TITLE
[BUG] [1.20.1] The game crashes if Shoulder Surfing is run together with Capes (Forge/Fabric), Cosmetica (Fabric) or other cape mods.

### ISSUE THREAD

**Issue by Tapacywka** [Exopandora/ShoulderSurfing#157]
### Description

The game crashes if Shoulder Surfing is run together with Capes (Forge/Fabric), Cosmetica (Fabric) or other cape mods.
This happens after updating Shoulder Surfing from 2.8.2 to 2.9+ (tried both 2.9.1, 2.9.2, and 2.9.3).
https://mclo.gs/EF3kDVH - latest.log
https://mclo.gs/q7My1B2 - debug.log
https://mclo.gs/xw0x11X - crash-report.txt

### Steps to Reproduce

1. Install Forge 47.2.20 / NeoForge 47.1.101 / Fabric 0.15.7 for Minecraft 1.20.1.
2. Install Shoulder Surfing 2.9+.
3. Install Capes 1.5.2 (Forge/Fabric) / Cosmetica 1.2.7 (Fabric).
4. Launch the game.

### Expected Behavior

The game should start up.

### Game Logs

Attached three logs in the description field

**Comment by Tapacywka** [comment]
The logs on NeoForge are given as an example. For Fabric, Fabric API & Forge Config API Port were additionally used.

**Comment by Tapacywka** [comment]
This is happening again with the 2.9.5 version of the game.
Exactly the same error.

**Comment by Tapacywka** [comment]
@Exopandora, That's weird. With a pre-generated config I managed to enter the game once. But literally when I log in again, it crashes again.

**Comment by Tapacywka** [comment]
https://mclo.gs/RwScPX8 - latest.log
https://mclo.gs/XTKhIvs - debug.log
https://mclo.gs/yLOY1jk - crash-report.txt

**Comment by Exopandora** [comment]
Your game crashes because of better third person, which  is unrelated to shoulder surfing.

**Comment by Tapacywka** [comment]
> Your game crashes because of better third person, which is unrelated to shoulder surfing.

I thought so too at first, but then I removed it from modifications and the crash happened again. And then I removed SSR and the game loaded. I tested on a clean instance with only SSR and Capes - the game crashes.

**Comment by Exopandora** [comment]
Please attach the crash log with just shoulder surfing and capes installed.

**Comment by Exopandora** [comment]
Does not crash on my machine. Tested with:
- Forge 47.2.20
- ShoulderSurfing-Forge-1.20.1-2.9.5
- capes-1.5.2+1.20-forge
- kotlinforforge-4.10.0-all

**Comment by Exopandora** [comment]
Closing this for now. If you still encounter any crashes in this context, feel free to reopen this issue.
