### ISSUE TITLE
[FEATURE] Compatibility with mod Crosshair Bobbing

### ISSUE THREAD

**Issue by LEAWIND** [Exopandora/ShoulderSurfing#161]
[Crosshair Bobbing](https://github.com/Krash220/CrosshairBobbingMod)

It works fine in first person mode, but there's no bobbing in shoulder surfing mode.

**Comment by Exopandora** [comment]
The mod disables itself when not in 3rd person, see https://github.com/Krash220/CrosshairBobbingMod/blob/main/game/fabric1.16.2/src/main/java/krash220/xbob/game/api/Render.java#L28
