### ISSUE TITLE
[BUG] [MC-VERSION] 1.18.2 Crash

### ISSUE THREAD

**Issue by EicoYT** [Exopandora/ShoulderSurfing#164]
### Description

I started working on a modpack in 1.18.2 when I added shoulder surfing minecraft crashed and didnt even create a crash report.
I installed earlier version and that fixed the problem.
Versions that have the problem are the 2 newest for 1.18.2 (2.9.5 and 2.9.6).

### Steps to Reproduce

I just put a bunch of mods together and the culprit was shoulder surfing, I tested shoulder surfing alone and it works fine so it has a problem with a different mod (I guess)

### Expected Behavior

of course it should just launch and not crash.

### Game Logs

https://gist.github.com/EicoYT/5d6b11862ad9ca419a9d6bbe77ba9447

### Other Mods

I dont know the mod that it has a problem with, you should see a modlist in the log

**Comment by Exopandora** [comment]
Thanks for the report. This is now fixed.
