### ISSUE TITLE
[BUG] [1.20.1] Armor trims don't show up

### ISSUE THREAD

**Issue by Maagick** [Exopandora/ShoulderSurfing#167]
### Description

Armor trims don't show up in game.

### Steps to Reproduce

1. Equip an armor item with an armor trim
2. F5 to look at yourself

### Expected Behavior

Armor trims to show up
They only show in UIs like inventory but not in the actual game.

### Screenshots

![image_2024-03-31_111227929](https://github.com/Exopandora/ShoulderSurfing/assets/165483342/4f6ce0e6-8660-44d0-92a1-4dff5cdd809e)
![image_2024-03-31_111235271](https://github.com/Exopandora/ShoulderSurfing/assets/165483342/c675fd11-67da-45c0-939d-2dd20171a830)

### Game Logs

https://mclo.gs/KRQ3CKh , https://gist.github.com/Maagick/25c64a2acc63fdc2b8a4a945b778f6d0

### Additional Information

They show up in inventory but not in game. Removing this mod fixed the issue so I know it's this one but I want to be able to keep it in the pack so help is appreciated. Thank you.

**Comment by Exopandora** [comment]
What version of shoulder surfing are you using? The logs suggest that you dont have it installed at all. This very bug was a known issue in earlier 2.9.x revisions. It should be fixed in 2.9.6+

**Comment by Exopandora** [comment]
Please update iris. It should fix the problem. If so, please close the issue.

**Comment by Maagick** [comment]
I am using 2.9.6, attempting to update Iris now and I'll get back to you if that works, thank you
