### ISSUE TITLE
3.0.0 Update of Shoulder Surfing Reloaded is not out for 1.12.2?

### ISSUE THREAD

**Issue by Titoo8899** [Exopandora/ShoulderSurfing#169]
### Description

Hi,
I have see the new Update and was happy new thinks and many changes what I love but I have on CurseForge and Modrinth no a 1.12.2 Versionsupdate to the new 3.0.0 Update see. Is the 1.12.2 not Approved on the website or why give it not a Update of this version?

### Steps to Reproduce

Look on CurseForge or Modrinth in the Changelog or in the Versions

### Expected Behavior

Then I search for the 1.12.2 Version have I hope the new 3.0.0 with Support for 1.12.2 MC Version to see

### Game Logs

Not a Game Bug

**Comment by Exopandora** [comment]
Unfortunately, Shoulder Surfing Reloaded will not receive any new updates for 1.12.2 due to technical limitations and is therefore end of support.

**Comment by Titoo8899** [comment]
oh this is sad the mod was so cool and this is bad to hear
