### ISSUE TITLE
Suggestion: having a dedicated key for Shoulder Surfing's 3rd person view

### ISSUE THREAD

**Issue by SepSol** [Exopandora/ShoulderSurfing#17]
Which only toggles between default 1st person view and Shoulder Surfing's 3rd person view. Obviously this key can be unbinded if someone doesn't like it.

Also an option in the config file for whether Shoulder Surfing should be on F5's camera cycle or not.

**Comment by Exopandora** [comment]
A keybind option will be implemented in the next version. But i dont really see a reason why you would need a config option to disable shoulder surfing in the f5 cycle.

**Comment by SepSol** [comment]
I only said that because I thought having options might be nice :)
But the first paragraph is what I think is gonna be useful.

**Comment by Exopandora** [comment]
I agree that its nice to have options but in this paticular case the cost/use factor is pretty high. It would need significant code changes and possibly rewrites to create a toggle switch for the shoulder surfing perspective. Its just not worth the effort

**Comment by SepSol** [comment]
I understand, you're right. Maybe for the time-being a seperate button for switching between the default first person and Shoulder Surfing will do the job.

Also is there a reason for when I change my shaders or texturepacks inside the game I get forced to Shoulder Surfing's third person every time? Is there a way to make it use the last view that the player was using?

**Comment by Exopandora** [comment]
This issue will be fixed for 1.14.4-1.21

**Comment by SepSol** [comment]
It's fixed, thanks.
