### ISSUE TITLE
[1.20.1] Crash on startup with Shoulder surfing 3.0.0

### ISSUE THREAD

**Issue by pastellarium** [Exopandora/ShoulderSurfing#170]
### Description

I'm unsure what conflict is causing the crash, and I have little to no idea how to diagnose that from the log file, so I'll put the log file here and hope that helps, If there's more information I can provide that would help, let me know.

### Steps to Reproduce

1. Start game
2. Crash

### Expected Behavior

Game begins as usual without crashing

### Game Logs

https://gist.githubusercontent.com/pastellarium/890ef66b432299d9dd4a5a0e0709cf33/raw/68149fdf23d67a8878f9a5c0fb2df9c4f08fb0c0/gistfile1.txt

**Comment by muhammedesadcomert** [comment]
Same issue, you can check my crash log also: https://mclo.gs/mi4F9iy

**Comment by Exopandora** [comment]
Thanks for the report. This looks like a compatibility issue to me, where some other mod optionally depends on an older version of shoulder surfing, as the game does not crash when no other mods are installed. The only way to debug this further is to find the conflicting mod, which can be done using the method described here: https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a

**Comment by Exopandora** [comment]
Please update spell engine to resolve the issue.
