### ISSUE TITLE
Incompatible with Camera Overhaul

### ISSUE THREAD

**Issue by DziwnyPanPL** [Exopandora/ShoulderSurfing#171]
### Description

Incompatible with [Camera Overhaul](https://modrinth.com/mod/cameraoverhaul)

### Minecraft version

1.20.1

### Incompatible mod name

Camera Overhaul

### Incompatible mod version

Camera Overhaul v1.4.0 / Shoulder Surfing 3.0.0

### Game Logs

https://mclo.gs/3kMIkam

**Comment by Exopandora** [comment]
This is a known incompatiblity, hence the message on startup. Only the authors of CameraOverhaul can fix this problem. Once they fix it, I will remove the incompatiblity constraint.

**Comment by DziwnyPanPL** [comment]
@Exopandora Generally the creators of the Camera mod will probably never update the mod again, all their media is dead, so sadge :<
