### ISSUE TITLE
water is invisible through a transparent player

### ISSUE THREAD

**Issue by EnderHane** [Exopandora/ShoulderSurfing#176]
### Description

![2024-04-28_23 14 27](https://github.com/Exopandora/ShoulderSurfing/assets/53217585/adda2fde-497b-438d-b289-935964a0a62b)
![2024-04-28_23 14 33](https://github.com/Exopandora/ShoulderSurfing/assets/53217585/921df7b2-cadd-4aea-9dd7-76426c63910a)

### Steps to Reproduce

NeoForge 47.1.104
Shoulder Surfing Reloaded 1.20.1-3.1.0
(no other mods)

### Minecraft version

1.20.1

### Game Logs

https://mclo.gs/O3vzqVZ

**Comment by Exopandora** [comment]
This is a bug of vanilla minecraft, there is nothing I can do about this.
