### ISSUE TITLE
Mouse Rotation Not Working with Shoulder Surfing Reloaded on Minecraft 1.19.2

### ISSUE THREAD

**Issue by sdy623** [Exopandora/ShoulderSurfing#179]
### Description

I'm experiencing an issue with the Shoulder Surfing Reloaded mod where the mouse rotation does not work when using the over-the-shoulder camera view. This problem occurs in Minecraft version 1.19.2.

## Expected Behavior
The camera view should rotate in response to mouse movements, allowing for adjustments to the player's field of view.

## Actual Behavior
The camera view remains static and does not respond to any mouse movements, effectively locking the player's field of view.

## Possible Solution
No known workaround at this time.

### Minecraft version

1.19.2

### Game Logs

https://mclo.gs/Pey0YQI

**Comment by Exopandora** [comment]
Thanks for the report. This is most likely a compatibility issue. Please follow the steps outlined in the [compatibility issue template](https://github.com/Exopandora/ShoulderSurfing/issues/new?assignees=&labels=compatibility&projects=&template=compatibility.yaml&title=Incompatible+with+MOD).

**Comment by Exopandora** [comment]
Superseded by #180
