### ISSUE TITLE
When loading a world, it always starts from ShoulderSurfing perspective

### ISSUE THREAD

**Issue by SepSol** [Exopandora/ShoulderSurfing#18]
It would be great if this option could be at least changed via the config file.

**Comment by Exopandora** [comment]
When you load the game (boot) the perspective will be changed to the configured perspective in the config file (default_perspective). After that the perspective will stay the same.

**Comment by SepSol** [comment]
Is there any way to make it use the last perspective the user used before exiting the game on next boot by default?

**Comment by Exopandora** [comment]
Why would you need that ? As i said you can set a default perspective when the game launches

**Comment by SepSol** [comment]
Because I want to distribute this to the players on my server and I want them to be able to play each time in their latest preferred perspective and don't have to switch each time. Not everyone in my server is familiar with how to edit config files.
