### ISSUE TITLE
Remember perspective not working on 1.20.1 3.1.0

### ISSUE THREAD

**Issue by Joe-Schmoe-123** [Exopandora/ShoulderSurfing#181]
### Description

No matter whether remember perspective is set to off, it always remembers the last perspective when switching to third person.

### Steps to Reproduce

Turn on or off "Remember last perspective".  Test in game.

### Minecraft version

1.20.1

### Game Logs

https://mclo.gs/SGHoysJ

**Comment by Exopandora** [comment]
Thank you for the report. This will be fixed in the next release.
