### ISSUE TITLE
Camera rotation does not reset when another mods changes perspective to shoulder surfing

### ISSUE THREAD

**Issue by Joe-Schmoe-123** [Exopandora/ShoulderSurfing#182]
### Description

Thank you so much for fixing the "remember last perspective" issue.  However, the issue still occurs with Epic Fight.  If you are in shoulder surfing mode and battle mode, and facing one direction, switch to first person/mining mode, face a different direction, and then switch to shoulder surfing/battle mode it will revert to the last perspective no matter what it is set to in the mod config. It didn't used to do this in older versions of Shoulder Surfing.

### Minecraft version

1.20.1

### Incompatible mod name

Epic Fight

### Incompatible mod version

20.7.4

### Game Logs

https://mclo.gs/VpbLdS8

**Comment by Exopandora** [comment]
Sorry, I do not understand the issue. "Remember last perspective" sets the perspective when lauching the game. After that, it will not be set again, as it is controlled by the user.

**Comment by Joe-Schmoe-123** [comment]
Oh, I guess I misunderstood what remember last perspective did.  Regardless, there is an issue if, say, you're facing north in shoulder surfing, then revert to first person, face south, then revert to shoulder surfing again you will be swapped to facing north.

**Comment by Exopandora** [comment]
Do you use the SSR keybind to switch perspectives or do you press F5?

**Comment by Joe-Schmoe-123** [comment]
I use a keybind, but it is also an issue if you have Epic Fight to set to auto-switch to third person when you select a weapon.
