### ISSUE TITLE
No "Skip Third Person Back Perspective" config?

### ISSUE THREAD

**Issue by KiraKayn** [Exopandora/ShoulderSurfing#187]
Theres a Skip Third Person Front Perspective config option, but not one for the Back perspective, where I literally can't do anything, cant turn over (basically vanilla) and is just useless in most scenarios considering theres already a back perspective from Shoulder Surfing.
![image](https://github.com/Exopandora/ShoulderSurfing/assets/145915364/f2ac0909-8d28-4d8a-b732-223b055f71ca)

**Comment by Exopandora** [comment]
Use `replace_default_perspective` to replace the default third person perspective with the shoulder surfing perspective.
