### ISSUE TITLE
Some incompatibilities with Mr. Crayfish's gun mod

### ISSUE THREAD

**Issue by adrianholz** [Exopandora/ShoulderSurfing#188]
### Description

https://github.com/Exopandora/ShoulderSurfing/assets/87616443/daa74671-d68c-4012-84f7-363ad8aa3699

So as seen in the video the weapon from MrCrayfish's gun mod produces a lot of recoil in the first person, and not at all on shoulder surfing. Would it be possible for the camera on shoulder surfing to also go up on shooting?

And also, when aiming (holding right click), the crosshair disappears. Is there a way to make it check for shoulder surfing perspective & right click and if so, zoom the camera & enable/replace the crosshair?

Version is 1.19.2 with 43.3.13 forge 

### Minecraft version

1.19.2

### Incompatible mod name

MrCrayfish's Gun mod

### Incompatible mod version

cgm-forge-1.19.2-1.3.7.jar

### Game Logs

https://mclo.gs/s4bP9wn

**Comment by Exopandora** [comment]
Thank you for the report, I will look into it.

> And also, when aiming (holding right click), the crosshair disappears. Is there a way to make it check for shoulder surfing perspective & right click and if so, zoom the camera & enable/replace the crosshair?

I can already tell you that this needs to be implemented by the authors of MrCrayfish's Gun mod.

**Comment by adrianholz** [comment]
Alright, thank you for addressing this issue.

About the zoom/crosshair replacement, I thought of an alternate solution. This issue could be fixed if there was a button the player could hold, while in shoulder surfing, to temporarily alternate to first person (in this case, the right mouse button, the same used to aim the gun). On release, return to shoulder surfing perspective. Would that be possible?

**Comment by Exopandora** [comment]
There is a possibility to automate this already to a certain extent. Simply set `crosshair_type` to `STATIC_WITH_1PP`, which will make you switch to first person whenever an item that is declared as "adaptive" in the config is either used or held by the player. Then you add the relevant items that should switch to first person to the `adaptive_crosshair_hold_items` list. You can also use a regular expression to match all items of cgm, so you do not need to type out all items: `cgm:.*`.

**Comment by adrianholz** [comment]
Unfortunately that wouldn't be an option for the modpack I'm making, as I'm aiming for it to be a third-person tactical shooter. The guns work as expected on shoulder surfing, apart from the aiming restrictions and recoil absence.

**Comment by Exopandora** [comment]
> Unfortunately that wouldn't be an option for the modpack I'm making, as I'm aiming for it to be a third-person tactical shooter

I see. Unfortunately, having a dedicated button for a very specific use case is not something I want to integrate.

As for the current status of the issue:
- Recoil now works in third person (see 8801f56)
- Crosshair rendering is explicitly disabled by cgm when using ads (see https://github.com/MrCrayfish/MrCrayfishGunMod/blob/1.19.X/src/main/java/com/mrcrayfish/guns/client/handler/CrosshairHandler.java#L118). This needs to be fixed by cgm. A fix would be to check for third person, and not disable the event:
```diff
- if(AimingHandler.get().getNormalisedAdsProgress() > 0.5)
+ if(AimingHandler.get().getNormalisedAdsProgress() > 0.5 && Minecraft.getInstance().options.getCameraType() == CameraType.FIRST_PERSON)
```
- Fov changes are only be applied by cgm when in first person (see https://github.com/MrCrayfish/MrCrayfishGunMod/blob/1.19.X/src/main/java/com/mrcrayfish/guns/client/handler/AimingHandler.java#L147). This needs to be fixed by cgm. A fix would be to remove the first person check:
```diff
- if(mc.player == null || mc.player.getMainHandItem().isEmpty() || mc.options.getCameraType() != CameraType.FIRST_PERSON)
+ if(mc.player == null || mc.player.getMainHandItem().isEmpty())
```

**Comment by adrianholz** [comment]
Alright! Thank you very much for your effort and dedication to this issue. This has helped me enormously.
Just a last and quick question: do I need to do something specific to compile this mod for version 1.19.2 with the additions integrated in [8801f56](https://github.com/Exopandora/ShoulderSurfing/commit/8801f56957c70a4814dc13fdbc5b4a439b59d83c)?

**Comment by Exopandora** [comment]
> Just a last and quick question: do I need to do something specific to compile this mod for version 1.19.2

Just checkout branch `1.19.2` and follow the [Building from Source](https://github.com/Exopandora/ShoulderSurfing?tab=readme-ov-file#building-from-source) section. If you only care about the forge build, you can also run `gradlew :forge:build`. This should skip the fabric build. I will also create a new release next week, so it will be available for everyone.

**Comment by adrianholz** [comment]
I've built the mod and placed it on my mods folder, but I get a crash and exit code 1 on startup.

Here is my [latest.log](https://mclo.gs/2mgsxT0)
