### ISSUE TITLE
Incompatible with Spartan Weaponry

### ISSUE THREAD

**Issue by LinePanda** [Exopandora/ShoulderSurfing#189]
### Description

When using a crossbow from Spartan Weaponry in 3rd person, the game will crash.

### Minecraft version

1.18.2

### Incompatible mod name

Spartan Weaponry

### Incompatible mod version

Spartan Weaponry : 3.0.1 Shoulder Surfing: 3.1.3

### Game Logs

https://mclo.gs/jYQPXID

**Comment by LinePanda** [comment]
Sorry, forgot to mention this happens on Forge 40.2.18

**Comment by LinePanda** [comment]
You also do not have to be in 3rd person for it to crash

**Comment by Exopandora** [comment]
Thanks for reporting, please see ObliviousSpartan/SpartanWeaponry#35.
