### ISSUE TITLE
Crash and exit code 1 on startup of CGM-compatible mod build

### ISSUE THREAD

**Issue by adrianholz** [Exopandora/ShoulderSurfing#190]
I've built the mod and placed it on my mods folder, but I get a crash and exit code 1 on startup.

Here is my [latest.log](https://mclo.gs/2mgsxT0)

_Originally posted by @adrianholz in https://github.com/Exopandora/ShoulderSurfing/issues/188#issuecomment-2106404204_

**Comment by adrianholz** [comment]
Yes, that unfortunately seems to be the case. I have created a test modpack with only Shoulder Surfing and the crash still happens.

Here is the [latest.log](https://mclo.gs/5z6QZRm)

**Comment by Exopandora** [comment]
Apparently it is bugged. I was able to reproduce your crash with a clean build. But if you execute `:forge:build` again, it works for some reason.

**Comment by adrianholz** [comment]
Yes, everything seems to be working perfectly now. Also, your suggestions have solved the crosshair disappearing and the camera not zooming in on aiming. Thank you very much.

I will attach the cgm file with the appropriate modifications here, as well as a working Shoulder Surfing build for anyone that has had the same issues as me.

[Shoulder Surfing + CGM 1.19.2.zip](https://github.com/Exopandora/ShoulderSurfing/files/15299495/Shoulder.Surfing.%2B.CGM.1.19.2.zip)
