### ISSUE TITLE
[Improvement] Add key mapping to disable decoupled camera

### ISSUE THREAD

**Issue by EuBruno1** [Exopandora/ShoulderSurfing#191]
Hi, thank you for this amazing mod.
I would like to sugest an improvement, for a key that disables the decoupled camera, as this will allow for better compatibility with some combat mods.
Thanks!

**Comment by Exopandora** [comment]
Thank you for the suggestion. Have you tried solving the issue with the adaptive item configs (see `adaptive_crosshair_hold_items` and `adaptive_crosshair_use_items`)?

**Comment by EuBruno1** [comment]
Wow, it worked great!
However the idea of a key to enable/disable the decoupled camera would still be useful when building, as it allows for more precise block placement as the block's rotation depends on the direction the player is facing (I.E. placing a chest in the wrong direction because the player is facing another direction).

Anyway, for the  combat the adaptive_crosshair_hold_items option works great!
Thank you!

**Comment by WallFl** [comment]
But how do you do that?

**Comment by Exopandora** [comment]
> However the idea of a key to enable/disable the decoupled camera would still be useful when building, as it allows for more precise block placement as the block's rotation depends on the direction the player is facing (I.E. placing a chest in the wrong direction because the player is facing another direction).
 
This has been fixed in the latest release. Please let me know if this issue can be closed, as there should no longer be a need for such a feature.

**Comment by ArcjerzForDayz** [comment]
Yo! I was also looking for something like this. Cuz its kinda uncomfortable having the camera not turn with the player. Could this be an actual feature of the mod?

**Comment by Exopandora** [comment]
> I was also looking for something like this. Cuz its kinda uncomfortable having the camera not turn with the player. Could this be an actual feature of the mod?

This sounds like you want to permanently disable the decoupled camera mode, which is already possible by setting `decoupled_camera` to `false` in the config file (`shouldersurfing-client.toml`). Does this already solve your problem?

**Comment by elijahjibben** [comment]
Hey! I was just going to come here to suggest the same feature. A toggle key for the decoupled camera would be great. I use this on a server with a very intricate spell system and the game looks great with the decoupled camera but in combat its necessary to have it disabled. A toggle for this feature would save a lot of time from going through 5+ menus just to toggle it!

**Comment by Exopandora** [comment]
Although the next version will have a dedicated keybind for toggling the camera coupling, I still recommend properly setting up the `adaptive_crosshair_hold_items` and `adaptive_crosshair_use_items` config options, which will automatically enable and disable the camera coupling depending on the item held or used.
