### ISSUE TITLE
Option to always orient the player body & head even if not holding a ranged item

### ISSUE THREAD

**Issue by Novaenia** [Exopandora/ShoulderSurfing#192]
currently when in decoupled mode, the player only turns to the crosshair when holding right mouse if they're either in reach of a block or holding a ranged item such as a shield or bow. an option to let the player turn their character regardless of this would be quite nice

**Comment by Exopandora** [comment]
Do you mean turning the player even if there is no target, or synchronizing the player rotation with the camera rotation? The former is already part of the next release and the later can be achieved by setting `decoupled_camera` to `false`.
