### ISSUE TITLE
Additional feature request for [camera.offset.multiplier]

### ISSUE THREAD

**Issue by Tapacywka** [Exopandora/ShoulderSurfing#194]
There are currently 2 multipliers available:
- camera.offset.multiplier.passenger.
- camera.offset.multiplier.sprint.

I propose to add a new type of multiplier:
- camera.offset.multiplier.aiming.

The camera is shifted to the specified XYZ coordinates during aiming with bow, crossbow, trident and other items that have RMB action (for example, staffs from RPG Series mods).
Below I'll show screenshots of what it should look like (roughly).

![2024-05-19_00 54 04](https://github.com/Exopandora/ShoulderSurfing/assets/71761232/624116a1-3650-4da3-86a8-a0e6d3ba4283)
![2024-05-19_00 55 25](https://github.com/Exopandora/ShoulderSurfing/assets/71761232/d259cf49-9d16-444f-9474-8b7450c40711)
![2024-05-19_00 56 32](https://github.com/Exopandora/ShoulderSurfing/assets/71761232/a323f32c-aa9a-48fb-ae42-c205dae102f2)
![2024-05-19_00 57 13](https://github.com/Exopandora/ShoulderSurfing/assets/71761232/d54788e5-9eeb-496a-bd1a-96a10f43e14d)

**Comment by Exopandora** [comment]
Thank you for the suggestion. This will be part of the next release, since it was very easy to implement. Note that this multiplier will be applied whenever the player is holding or using an adaptive item (as configured in the config file). If `0.0` is configured as the default camera offset for a given axis, the multiplier of that axis will have no effect, as it is a multiplier. As a workaround, you could configure a very low value, for example `0.01`, and a very large multiplier, for example `75`, so that the resulting value (`0.01 * 75 = 0.75 [blocks]`) will have a suitable order of magnitude.

**Comment by Tapacywka** [comment]
> Thank you for the suggestion. This will be part of the next release, since it was very easy to implement. Note that this multiplier will be applied whenever the player is holding or using an adaptive item (as configured in the config file). If `0.0` is configured as the default camera offset for a given axis, the multiplier of that axis will have no effect, as it is a multiplier. As a workaround, you could configure a very low value, for example `0.01`, and a very large multiplier, for example `75`, so that the resulting value (`0.01 * 75 = 0.75 [blocks]`) will have a suitable order of magnitude.

Ooh, yeah. That's very smart. Thanks so much for your suggestion and for accepting mine! Could you please tell me if this works if I don't want my character to be transparent at 0.0 X position, but I want this feature to remain, for example, when I run under trees or something else is above me? Because now I turned off this option, because my character becomes transparent forever.

**Comment by Exopandora** [comment]
> Could you please tell me if this works if I don't want my character to be transparent at 0.0 X position, but I want this feature to remain, for example, when I run under trees or something else is above me? Because now I turned off this option, because my character becomes transparent forever.

Unfortunately, this is not possible, as the transparency is directly dependant on the distance between the crosshair and the center of the player.

**Comment by Tapacywka** [comment]
> Unfortunately, this is not possible, as the transparency is directly dependant on the distance between the crosshair and the center of the player.

By the way, while the update with this isAiming feature is not out yet, will you be able to make a smooth transition between offsets? As far as I understand, you can't make a transition between first-person and third-person camera, but here only the third-person camera changes position. So, theoretically, it is possible?

**Comment by Exopandora** [comment]
> By the way, while the update with this isAiming feature is not out yet, will you be able to make a smooth transition between offsets? As far as I understand, you can't make a transition between first-person and third-person camera, but here only the third-person camera changes position. So, theoretically, it is possible?

Offset changes within the shoulder surfing perspective use interpolation. See existing offset multipliers or ladder centering.
