### ISSUE TITLE
Spinning lock on camera bug

### ISSUE THREAD

**Issue by SilverOracle** [Exopandora/ShoulderSurfing#195]
### Description

When the target is locked a camera starts spinning wildly (while tying to move in 3rd person behind the shoulder) 

### Steps to Reproduce

1. install Shoulder Surfing + lock on (fabric)
2. start the game
3. turn the camera to shoulder wiew
4. lock any mob
5. turn on "you spin me right round"
6. enjoy

### Minecraft version

fabric 1.20.1

### Game Logs

theres no crash reports

**Comment by Exopandora** [comment]
Thank you for the report. This is someting that needs to be figured out by the authors of lock on.
