### ISSUE TITLE
Incompatible with Create Trains

### ISSUE THREAD

**Issue by NolanHewitt** [Exopandora/ShoulderSurfing#197]
### Description

Trains have a unique third person perspective while in the driver seat to allow you to see properly in third person. This mods camera overrides that.

### Minecraft version

1.20.1

### Incompatible mod name

Create Fabric

### Incompatible mod version

Any/Newest

### Game Logs

https://mclo.gs/wb5j7GO

**Comment by Exopandora** [comment]
Thank you for the report. I will look into it. I made some changes literally yesterday that could help solve this issue. However, while testing, I noticed more serious issues when using create mod and shulder surfing reloaded together, such as the ray casting of the player not working correctly for create trains.
