### ISSUE TITLE
Incompatible with Better Third Person

### ISSUE THREAD

**Issue by MyreneGourem** [Exopandora/ShoulderSurfing#198]
### Description

When trying to start Minecraft while both ShoulderSurfing and better Third Person is installed the game will not start, instad this shows up:
![Screenshot 2024-05-21 180031](https://github.com/Exopandora/ShoulderSurfing/assets/115667278/66b9489e-be7b-4af0-b3e7-4922002b9781)

### Minecraft version

1.20.4

### Incompatible mod name

Better Third Person

### Incompatible mod version

1.9.0

### Game Logs

https://mclo.gs/4zlUlSE

**Comment by Exopandora** [comment]
This is intentional, because the mods no longer work together, as of Shoulder Surfing Reloaded 3.0.0. Start up the game without better third person and you will see that you do not need it.
