### ISSUE TITLE
Incompatible with MOD Iris 1.7.0

### ISSUE THREAD

**Issue by Nilinking** [Exopandora/ShoulderSurfing#199]
### Description

The mod does not render the armor over the player when shaders are on. Tested on Iris 1.7.0 with Complementary Shaders and Photon shaders

### Minecraft version

1.20.4

### Incompatible mod name

Iris Shaders

### Incompatible mod version

1.7.0

### Game Logs

https://mclo.gs/q1v9x3Q

**Comment by Exopandora** [comment]
This might be due to the shader pack not supporting translucent armor. Here is a screenshot of it working using iris 1.7.0 with complementary reimagined shaders on minecraft 1.20.4:

![2024-05-21_23 24 42](https://github.com/Exopandora/ShoulderSurfing/assets/18708736/8d5c9910-fd51-44a0-a02f-c67a6c5d2548)

**Comment by Nilinking** [comment]
I did some testing with different shaders and you are right. However, would it be posible to disable the transparency renderer if the adjust_player_transparency setting is disabled to improve compatibility? all these tests were done with that setting on "false", yet it still affects the rendering of the player.

Thanks!

TESTING
---------------------------------------------------------------------------------------------------------------------

This is what happens with Photon Shader. note there is a faint "alpha shadow" where my elytra should be.
![image](https://github.com/Exopandora/ShoulderSurfing/assets/4532732/e72c6467-9b26-49ad-a224-3f7d895e3e11)

With the bliss shader is a similar story, Alpha issues with the elytra and armor, at least they are visible here but you can see trough.
![image](https://github.com/Exopandora/ShoulderSurfing/assets/4532732/e8fa850a-7c58-43de-b9f6-917c08c698f6)

BSL shaders work correctly
![image](https://github.com/Exopandora/ShoulderSurfing/assets/4532732/048336ec-4c62-4c0f-a10b-ed4053f03cb0)

Complementary Reimagined works correctly
![image](https://github.com/Exopandora/ShoulderSurfing/assets/4532732/9924cb10-be90-4926-bf04-bc096c7f6fe8)
