### ISSUE TITLE
Crossbow causes Inventory GUI and Pause menue to shift left

### ISSUE THREAD

**Issue by SepSol** [Exopandora/ShoulderSurfing#20]
When I use crossbow in Shoulder Surfing perspective with:
`crosshair_type = "ADAPTIVE"`
and open a chest, inventory, pause, or even open [World Handler's](https://www.curseforge.com/minecraft/mc-mods/world-handler-command-gui) GUI, all the elements of the HUD and GUI are shifted to left:

![image](https://user-images.githubusercontent.com/47871887/68111586-b699de00-ff04-11e9-83ab-a06b768e9278.png)

**Comment by Exopandora** [comment]
Must be an incompatibility issue with shaders or jei (most likely shaders)

**Comment by Exopandora** [comment]
The only way to fix that on my side is to disable crosshair movement when a gui is open which can lead to the following:
(The crosshair is not pointing at the selected block when the chat is opened)

![2019-11-04_16 58 37](https://user-images.githubusercontent.com/18708736/68135793-86face00-ff24-11e9-85be-2513b10d5b46.png)

**Comment by Exopandora** [comment]
Note: This does not happen with just shoulder surfing installed

**Comment by Exopandora** [comment]
I tested it with shaders (OptiFine_1.14.4_HD_U_F4, Forge 28.0.101) and the issue did not appear. Try setting the render/shader resolution to 1.0x

**Comment by SepSol** [comment]
Sorry, been busy past few days. My settings is on 1.0x and it still shifts left. I even turned off the shaders and I still seem to get the issue. I think I might have figured out where the problem lies though. It seems like the amount that the screen shifts is related to the amount the target is shifted from the center of the display. I use the ShoulderSurfing perspective really up close and to the side, in this situation if you get too close to a block and target it and then press pause for example, the shift would be pretty noticeable. Also the direction of the shift is related to the shoulder which the camera is on. Hope this helps!

**Comment by Exopandora** [comment]
I know that this issue is related to the shift of the crosshair as i encountered it in development. Please press `F3` + `C` ingame for 10 seconds and post the log file

**Comment by SepSol** [comment]
I didn't know that you can crash your own game! That would come in handy in multiplayer :p 
Here's the [crash-report](https://gist.github.com/SepSol/654e3afdb6e22429a3d0257d1ad0fa1d).

**Comment by Exopandora** [comment]
Can you name me a mod of yours that modifies the crosshair ?

**Comment by Exopandora** [comment]
Or a mod that has a special crosshair for some item ?

**Comment by SepSol** [comment]
Maybe FreeLook, idk.

**Comment by SepSol** [comment]
> Or a mod that has a special crosshair for some item ?

No i don't have any.

**Comment by Exopandora** [comment]
Well i had a possible fix in mid but as it turns out its already in the code to prevent issues like that. I guess there is nothing to be done on my side. My advice is that you isolate this issue to a specific mod and report a bug on there.

**Comment by SepSol** [comment]
Ok, I'll try to figure it out and report it. It's not a big issue for me eversince you've fixed the STATIC_WITH_1PP :p
