### ISSUE TITLE
[BUG] Crash when loading into world [Fabric 0.15.11/1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [Exopandora/ShoulderSurfing#200]
### Description

Crash whenever trying to load into world.

### Steps to Reproduce

Load with Iris already on

Load into world

Crash

### Minecraft version

1.20.1

### Game Logs

https://mclo.gs/gNWT7zB

**Comment by Tapacywka** [comment]
Try install this mod https://modrinth.com/mod/iris-flw-compat

**Comment by pokesmells** [comment]
![image](https://github.com/Exopandora/ShoulderSurfing/assets/33227568/8b674a28-227d-4b9a-ae40-9c8c5a53f2e7)

already present and active

**Comment by Exopandora** [comment]
Thank you for reporting the issue, I will look into it.

**Comment by Exopandora** [comment]
This has already been resolved in #201. Thanks again for reporting!
