### ISSUE TITLE
CGM compat disabled after codebase refactor

### ISSUE THREAD

**Issue by zaeonNineZero** [Exopandora/ShoulderSurfing#202]
### Description

The latest codebase refactor (at least on the 1.19.2 branch) appears to have disabled the CGM compat originally added in 3.2.0. I imagine that the compat mixin is simply not being activated, rather than the mixin itself having broken code or anything like that.

### Steps to Reproduce

1. Open any world and give yourself any gun from CGM or its addons.
2. Switch to the Shoulder Surfing camera.
3. Shoot.

### Minecraft version

1.19.2 - Minecraft Forge 43.3.9

### Game Logs

https://mclo.gs/QDATbEx

### Additional Information

I'm working on a fork of CGM that includes several additional features, including extra Shoulder Surfing compat support. Feel free to reach out to me if you'd like more information.

**Comment by Exopandora** [comment]
Thanks for reporting this one! I did not yet have the time to tested it outside the dev environment. It is fixed now.
