### ISSUE TITLE
add config setting for sound centering when playing in third person. 

### ISSUE THREAD

**Issue by whipeoff** [Exopandora/ShoulderSurfing#205]
Add config setting for sound centering when playing in third person. 

All the sounds that the player makes (strike with a sword, eat, walk, shoot from a bow) when playing from a third person always come from one of the sides (left or right), which after a while really gets stuck, because most of the time only one ear works and the other sits in complete silence

**Comment by Exopandora** [comment]
Thank you for the feedback. I agree, and this feature will part of the next release.

**Comment by whipeoff** [comment]
will that thing be available for 1.20.1 / 1.12.2 ?

**Comment by Exopandora** [comment]
The feature is available since Shoulder Surfing 4.0.0, which is avilable for 1.16[.2-5], 1.18[.1-2], 1.19[.1-2], 1.20[.1], 1.20.4, 1.20.6 and 1.21.
