### ISSUE TITLE
Let the head rotate with the camera when decoupled

### ISSUE THREAD

**Issue by Deleca7755** [Exopandora/ShoulderSurfing#206]
I always wanted to enjoy third person and have been coping for the perfect third person mod
_[BetterThirdPerson](https://modrinth.com/mod/better-third-person)_ was almost there but It doesn't have transparency when you get close, which I feel Is like a basic thing needed to make a usable third person. Is It Impossible to see what you're doing when getting wood after a few blocks or do I just have a skill Issue?

The main thing I like from _BTP_ Is how you can still rotate your head with the camera. Like whether you're facing forward or backwards, turning the camera up makes you look up and turning the camera down makes you look down. For example:
![btp](https://github.com/Exopandora/ShoulderSurfing/assets/46870340/6cd82ca7-1bb7-419a-a31c-b9e88f6f6ff0)
I like being able to look at things without moving. This makes It look less awkward when doing things and having the head Immediately snap Into place

Would appreciate, I just want to be able to play In third person without Issues
Also, do you backport updates?... Currently playing on 1.20.1 because a lot of mods I wanted weren't updated...

Thank you for your work 🙏🏽

**Comment by Exopandora** [comment]
Thank you for the feedback. This will be configurable via `sync_player_x_rot_with_inputs` in the next release.

**Comment by Exopandora** [comment]
FYI: The config option `sync_player_x_rot_with_inputs` will be renamed to `player_x_rot_follows_camera` in the next release of SSR (4.3.0).

**Comment by Deleca7755** [comment]
Yes, and I see you've added both X and Y rotation. Thank you so much!!! I wanted to request that as well but felt bad about It. The mod Is perfect for me now. Know the Issue's closed but I really wanted to show appreciation for It. So grateful for your consistent efforts and consideration 🤟🏽
