### ISSUE TITLE
Error when rolling with parcool

### ISSUE THREAD

**Issue by HeyRicar** [Exopandora/ShoulderSurfing#207]
### Description

When you use the "parcool" mod, and you roll forward everything is fine, the problem is when you roll the other way
This didn't happen before

### Steps to Reproduce

https://github.com/Exopandora/ShoulderSurfing/assets/118484218/cb68d22c-a108-4278-bd54-ea6368028b24

### Minecraft version

1.20.1

### Game Logs

https://mclo.gs/j1YofQu

**Comment by Exopandora** [comment]
Thank you for the report. What exactly do you mean by "before"?

**Comment by HeyRicar** [comment]
In the version "ShoulderSurfing-Forge-1.20.1-2.9.6" not having that camera movement, everything worked fine

https://github.com/Exopandora/ShoulderSurfing/assets/118484218/2c316797-db48-4b07-afbe-5b0c160bae07

**Comment by Exopandora** [comment]
Thanks for clarifying. You can still configure Shoulder Surfing to behave the same way as in older versions. In this case, you need to set `decoupled_camera` to `false`, and optionally change `crosshair_type` to `ADAPTIVE`.

After investigating the issue for some time, I suggest reporting this to the authors of parcool. They need to account for the look vector of the camera when computing the direction of the dodge, roll, etc. I see no real way of fixing this on my end.

**Comment by Exopandora** [comment]
Closing this, as the compatibility issue needs to be fixed by parcool.
