### ISSUE TITLE
Set keys to turn player

### ISSUE THREAD

**Issue by Fireflexor** [Exopandora/ShoulderSurfing#209]
**Describe your feature**
currently you are able to make the player turn when performing various actions, such as attacking, interracting, and picking blocks. some mods which i am using this with use custom keybinds for some item abilities, which do not rotate the player on use. i suggest being able to add a list of keys which when pressed will make the player face the direction the camera is pointing, to allow compatibility with such mods.

**Comment by Exopandora** [comment]
This is already possible using the `adaptive_crosshair_hold_items` and `adaptive_crosshair_use_items` config options.
