### ISSUE TITLE
Can no longer pull back view in v.4 

### ISSUE THREAD

**Issue by Joe-Schmoe-123** [Exopandora/ShoulderSurfing#210]
### Description

In previous versions I could pull back my view much further by pressing the down arrow.  In v4 I am locked with the default distance.  Up, left, and right still work, but not down/back. 

### Steps to Reproduce

Press the down arrow to pull back the view

### Minecraft version

1.20.1

### Game Logs

.

**Comment by Exopandora** [comment]
Thank you for the report, this will be addressed soon.
