### ISSUE TITLE
Ability to disable laser pointer for bow aiming

### ISSUE THREAD

**Issue by Joe-Schmoe-123** [Exopandora/ShoulderSurfing#211]
Currently when you aim a bow it generates a laser pointer for aiming.  I would like to be able to disable this but there doesn't seem to be a way to do so.

**Comment by Exopandora** [comment]
Can you upload a screenshot of it in action? If you mean a green line that goes from the head of the player to the crosshair, thats a feature of epic fight, not Shoulder Surfing.

**Comment by Joe-Schmoe-123** [comment]
My bad.  Sorry!
