### ISSUE TITLE
Incompatible with Camera Utils

### ISSUE THREAD

**Issue by PingGai** [Exopandora/ShoulderSurfing#213]
### Description

**Error Report Analysis by Kimi AI**
- Crash Phase: During the game initialization process
- Exception Type: `java.lang.RuntimeException`
- Reason for Error: Mixin transformation of `net.minecraft.class_4184` failed
- Classes and Methods Involved:
  - `net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray`
  - `org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins`
  - `org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject`
- Error Details: A critical injection failure occurred in `shouldersurfing.common.mixins.json:MixinCamera` from the mod shouldersurfing; the injection check failed.

### Minecraft version

1.20.6

### Incompatible mod name

Camera Utils

### Incompatible mod version

ShoulderSurfing Fabric 4.0.0, 4.1.0, 4.1.1 with Camera Utils 1.20.6-1.0.9

### Game Logs

https://mclo.gs/hWWMIOJ

**Comment by Exopandora** [comment]
Thanks for reporting. In versions prior to 4.0.0, Shoulder Surfing Reloaded essentially overwrote the camera position whenever the player was in shoulder surfing mode. To improve compatibility with other mods, such as Camera Overhaul and OptiFine, this implementation was changed. Unfortunaly, Camera Utils modifies the excat same line of the vanilla minecraft code that Shoulder Surfing Reloaded needs to modify for its functionality, resulting in the crash you reported and making it impossble to resolve this conflict. For now, the mods will remain incompatible, sorry.
