### ISSUE TITLE
Incompatible with Better Third Person

### ISSUE THREAD

**Issue by Shanky113** [Exopandora/ShoulderSurfing#215]
### Description

My shoulder camera is completely broken. It moves with my mouse (I don't think it's supposed to do that) and no matter what button I press it moves my character in the same direction. I made sure that it wasn't the free look setting and it's not. I just wanted a nicer third person experience by combining it with the Better Third Person mod and for some reason the Better Third Person mod works but Shoulder Surfing is completely broken.

https://github.com/Exopandora/ShoulderSurfing/assets/173206802/2caab8fe-0ef1-475b-8507-ba4d0d516c8a

### Steps to Reproduce

There's not any steps to reproduce as it was like this as soon as I installed the mod. :P

### Minecraft version

1.20.1

### Game Logs

https://mclo.gs/pT8139R

### Additional Information

this make big sad

**Comment by HemsX24** [comment]
it used to work with older version of shoulder surfing too in 1.18.2

**Comment by Exopandora** [comment]
As of version 3.0.0, Shoulder Surfing Reloaded features a "decoupled camera" mode. When enabled (default), the player rotation (and movement) will be decoupled from the camera roration. This is comparable to what Better Third Person tried to achieve. Having both installed at the same time regardless, leads to undefined behavior, as you demonstrated in the video. This is why the fabric and neoforge builds will refuse to load the game when an incompatible mod is installed (not possible on forge). Long story short, uninstall Better Third Person and any other incompatible mods listed in the [compatibility section of the README](https://github.com/Exopandora/ShoulderSurfing?tab=readme-ov-file#compatibility) and everything should work as expected.

**Comment by Shanky113** [comment]
> As of version 3.0.0, Shoulder Surfing Reloaded features a "decoupled camera" mode. When enabled (default), the player rotation (and movement) will be decoupled from the camera roration. This is comparable to what Better Third Person tried to achieve. Having both installed at the same time regardless, leads to undefined behavior, as you demonstrated in the video. This is why the fabric and neoforge builds will refuse to load the game when an incompatible mod is installed (not possible on forge). Long story short, uninstall Better Third Person and any other incompatible mods listed in the [compatibility section of the README](https://github.com/Exopandora/ShoulderSurfing?tab=readme-ov-file#compatibility) and everything should work as expected.

Thanks
