### ISSUE TITLE
Can't edit configs in the latest modmenu 10.0.0

### ISSUE THREAD

**Issue by sdy623** [Exopandora/ShoulderSurfing#216]
### Description

Can't edit configs in the latest modmenu

### Steps to Reproduce

Can't edit configs in the latest modmenu
it is gray

### Minecraft version

1.20.6

### Game Logs

...

**Comment by Exopandora** [comment]
In order to edit configs ingame, you need to install a separate mod, for example, ForgeConfigScreens or Configured. Although the first one may have some loading issues as outlined [here](https://github.com/Fuzss/forgeconfigscreens/issues/28) and the later one will only work for forge.
