### ISSUE TITLE
Game crashing with mod

### ISSUE THREAD

**Issue by shin252** [Exopandora/ShoulderSurfing#217]
### Description

so I play with a lot of mods and everything is fine but when I added the shoulder surfing mod, it does not work and the game gives me this error:

" The game crashed whilst exception in server tick loop
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_9236_()" because the return value of "com.github.exopandora.shouldersurfing.api.model.PickContext.entity()" is null "
exit code is -1

the forge version is 47.3.1
I would try and see what causes the issue myself but I am no expert in debugging and coding unfortunately

### Steps to Reproduce

unknown

### Minecraft version

1.20.1

### Game Logs

https://mclo.gs/x0JGOhw

**Comment by Exopandora** [comment]
Thanks for reporting! The crash was caused by Project Expansion, and will be fixed in the next release of Shoulder Surfing Reloaded.
