### ISSUE TITLE
incompatibility with Nimble

### ISSUE THREAD

**Issue by SylisMC** [Exopandora/ShoulderSurfing#22]
Hey, I love shoulder surfing, it makes 3rd person playable. And nimble is an awesome athetic mod that adds a few camera tweaks to the game, adding a transition from first to third person. and auto 3rd person when mounting, or using an elytra.

The two mods could work so smoothly together to make for fantastic game-play. but unfortunately they conflict with each other a little. when nimble puts you in 3rd person manually apon joining the world. it works fine, but as soon as you manually change it, shoulder surfing completely stops working.

I inquired about it with nimble and they "I checked Shoulder Surfing's source codes. There are too many incompatibilities. It will be much easier if Shoulder Surfing can implement its own transition."

I think making a compatibility patch or integrations would make for awesome gameplay
https://www.curseforge.com/minecraft/mc-mods/nimble
Thanks

**Comment by Exopandora** [comment]
There is no simple way to make a compatibility patch or integration with nimble. The only way is a full nimble rewrite to interpolate between perspectives in a more open way or for me to implement equivalent functionality. But i currently do not have the time to do this, sorry.
