### ISSUE TITLE
When Holding a Ranged Weapon (Armed Crossbow) Or Drawing One (Bow) Zoom In

### ISSUE THREAD

**Issue by myPI314by** [Exopandora/ShoulderSurfing#221]
When the player is holding a weapon like a drawn bow or a loaded crossbow (Compatibility could be determined if Fabric or Forge has a standard class for this) , the camera zooms in closer to the player like many games with this camera perspective do. Similar to how Leawind's Third Person does it.

**Comment by Exopandora** [comment]
Thanks for the suggestion. This can already be done using the config option `camera.offset.multiplier.aiming.multiplier_offset_z`.
