### ISSUE TITLE
without decoupled camera, crosshair aiming is not precise

### ISSUE THREAD

**Issue by glutaminus** [Exopandora/ShoulderSurfing#222]
without decoupled camera, player is not looking directly at crosshair, making aiming not precise.
while I know that option of [player.turning] is only for decoupled camera, I see no reason why we don't allow both camera option to have a precise crosshair.

Ps.  I also want player to look at crosshair all the time, unlike we have in [player.turning] where you need to do some certain events like attack/interact first (because in my custom server I have some custom skills that doesn't use those event eg. press 1 to shoot fireball at forward target location, but with current mod it's not aiming toward crosshair so it's not precise)

**Comment by Exopandora** [comment]
> without decoupled camera, player is not looking directly at crosshair, making aiming not precise.

The rotation of the players' head is independent of the position you are selecting with your crosshair. Whenever you are aiming (determined by `adaptive_crosshair_hold_items`, `adaptive_crosshair_hold_item_properties`, `adaptive_crosshair_use_items`, `adaptive_crosshair_use_item_properties`), the player will look at the position of your crosshair. This can be observed when shooting the bow.

>  I also want player to look at crosshair all the time

In this case, you can simply configure `adaptive_crosshair_hold_items` to `[".*"]`, which will match every item.
