### ISSUE TITLE
support for midnight controls: allow joysticks to manipulate camera movment

### ISSUE THREAD

**Issue by TheDiamondSquidy** [Exopandora/ShoulderSurfing#227]
Currently the mod Midnight Controls which adds controller support, cannot manipulate the camera in shoulder surfing mode using a joystick.

Mod: midnightcontrols 1.9.4
mc version 1.20.4

**Comment by Exopandora** [comment]
Thanks for reporting. This needs to be resolved by the authors of Midnight Controls. Please consider opening an issue on their repo. Alternatively, you can use a mod called Controllify, which works without issue.
