### ISSUE TITLE
Neoforge 21.0.82 changes crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [Exopandora/ShoulderSurfing#228]
### Description

![image](https://github.com/user-attachments/assets/e746485e-9b26-4a4d-9ae4-deee9ed38016)
ShoulderSurfing-NeoForge-1.21-4.1.5

### Steps to Reproduce

.

### Minecraft version

1.21

### Game Logs

https://pastebin.com/Krbji737

**Comment by Exopandora** [comment]
Thanks for reporting! Please forward this to the authors of [Forge Config API](https://github.com/Fuzss/forgeconfigapiport) port, as they need to update their code for the new NeoForge version.
