### ISSUE TITLE
Zoom doesn't work on latest release

### ISSUE THREAD

**Issue by MCYCShadow** [Exopandora/ShoulderSurfing#23]
Greetings,

In the latest version there is a bug that prevents from zooming in.
The only movement possible is left and right.
Little view on the functionality here: [Click](https://gfycat.com/anchoredpassionateeuropeanfiresalamander)
It would be realy nice to get closer to the character to get the result many are looking like in TR. RE.
It works with optifine and shaders now, which is good. 
Toggle shoulder and switch perspective is working as well.

Stay healthy

**Comment by Exopandora** [comment]
Thanks for the report. A new version will be available shortly.
Sidenote: Optifine is working on the latest version because i made some compatibility changes. The only thing i cant fix is the crosshair.
