### ISSUE TITLE
Disable the Crosshair thing

### ISSUE THREAD

**Issue by miezukie28** [Exopandora/ShoulderSurfing#230]
when you try to break a block behind your head goes to it and you break it

i god banned for cheating on hypixel because of this mod

**Comment by Exopandora** [comment]
> when you try to break a block behind your head goes to it and you break it

This is how the static crosshair works. You would need to use the dynamic crosshair instead.

> i god banned for cheating on hypixel because of this mod

I'm sorry to hear that, but also expected, since you might have an advantage over other players when using the mod.
