### ISSUE TITLE
Camera error with MedievalWeapons

### ISSUE THREAD

**Issue by KorvoZ** [Exopandora/ShoulderSurfing#231]
### Description

When MedievalWeapons is installed, the character keeps rotating when the camera rotates, preventing from seeing the character's face. The game is heavily modded, but I did some tests and I can confirm that the problem is MedievalWeapons

![mine-ezgif com-optimize](https://github.com/user-attachments/assets/fe357a21-a1ca-435f-b401-6f3ab760a3fb)

### Minecraft version

1.20.1

### Incompatible mod name

MedievalWeapons (https://modrinth.com/mod/medievalweapons)

### Incompatible mod version

1.4.8

### Game Logs

The game launchs, no need to upload a log.

**Comment by Exopandora** [comment]
Please see the [compatibility section](https://github.com/Exopandora/ShoulderSurfing?tab=readme-ov-file#compatibility) of the readme as stated in the issue template.
