### ISSUE TITLE
Incompatible with Create (latest ver)

### ISSUE THREAD

**Issue by Proxwian** [Exopandora/ShoulderSurfing#233]
### Description

Can't launch minecraft with ShoulderSurfing-Forge-1.20.1-4.2.0

### Minecraft version

1.20.1

### Incompatible mod name

Create

### Incompatible mod version

0.5.1f

### Game Logs

[crash-2024-07-22_03.17.25-client.txt](https://github.com/user-attachments/files/16326698/crash-2024-07-22_03.17.25-client.txt)

**Comment by Exopandora** [comment]
The crashlog indicates that your game crashes because of Embeddium and shows no relation to Shoulder Surfing Reloaded or Create mod. Have you tried starting the game without Embeddium?

**Comment by Proxwian** [comment]
Why I would do that? Embeddium is more important for me that ShoulderSurfing. Also, previous version working just fine

**Comment by Exopandora** [comment]
> Why I would do that?

This is useful for isolating the problem. Regardless, I was able to reproduce the issue and there was indeed a problem with the create mod compatibility. A fix will be available soon. Thanks for reporting.

**Comment by Exopandora** [comment]
Completed in 4cecbb4
