### ISSUE TITLE
Shadows get moved too

### ISSUE THREAD

**Issue by MCYCShadow** [Exopandora/ShoulderSurfing#24]
I noticed that on the latest release shadows drawn by shaders are also getting moved when the player moved the camera.
I guess this is due to the nature of the shaders but could there be a fix for that?
I am thinking of a solution to tell Minecraft that the anchor point aka original camera is still in the players head but you use the third person cam instead.

Keep up the work.

**Comment by MCYCShadow** [comment]
Here is a gif to showcase this: [Click](https://gfycat.com/leancolorfulindochinahogdeer)

**Comment by Exopandora** [comment]
Switching to the dynamic crosshair might help but this is really an issue of optifine. The is not much i can do on my side atm because of #21

**Comment by Exopandora** [comment]
If you want this fixed you should submit an issue at the optifine repo
