### ISSUE TITLE
collapse

### ISSUE THREAD

**Issue by zc1108aaa** [Exopandora/ShoulderSurfing#241]
### Description

0

### Steps to Reproduce

0

### Minecraft version

4.4.0

### Game Logs

1

### Additional Information

[latest - 副本.log](https://github.com/user-attachments/files/16862803/latest.-.log)
0
[crash-2024-09-04_16.00.38-client.txt](https://github.com/user-attachments/files/16862808/crash-2024-09-04_16.00.38-client.txt)

**Comment by Exopandora** [comment]
The crash is caused by Disenchantment Edit Table. It is most likely caused by using an outdated version of the nightconfig library, which is bundled in or Forge Config API Port. Try opening an issue at Disenchantment Edit Table or Forge Config API Port.
