### ISSUE TITLE
Player transparency fails to work with Entity Model Features (EMF) when using a player animation pack

### ISSUE THREAD

**Issue by deiphiz** [Exopandora/ShoulderSurfing#242]
### Description

I am using the [Fresh Moves](https://modrinth.com/resourcepack/tras-fresh-player) resource pack which requires the latest version of EMF + ETF to be installed to work. Unfortunately when the resource pack is enabled the transparency feature of Shoulder Surfing stops working completely. The player model can still disappear when the camera is within the specified range but transparency won't happen. Issue goes away when resource pack is disabled.

Downgrading to a lower version of EMF (2.1.3) actually does restore the transparency however the Fresh Moves and Fresh Animations resource packs are broken on those older versions.

https://github.com/user-attachments/assets/f058a9d3-0a2f-460a-b8e6-e8084b4811e2

See attached video for demonstration.

### Minecraft version

1.21.1

### Incompatible mod name

Entity Model Features (EMF)

### Incompatible mod version

2.2.4

### Game Logs

https://mclo.gs/fPpP9E3

**Comment by Exopandora** [comment]
Thanks for reporting. A fix will be part of the next release.

**Comment by Traben-0** [comment]
nice
