### ISSUE TITLE
Curseforge version error

### ISSUE THREAD

**Issue by Shizoukia** [Exopandora/ShoulderSurfing#244]
### Description

https://www.curseforge.com/minecraft/mc-mods/shoulder-surfing-reloaded/files/all?page=1&pageSize=20&version=1.21

You mistakenly placed version 1.21.1 in the 1.21 version tag
Please repair him in a timely manner

I thought 1.21.1 and 1.21 were compatible. I tried downloading them, but it caused an error on the client. After checking for some time, I realized that 1.21.1 and 1.21 are completely incompatible
The developer mistakenly marked the mod version 1.21.1 as version 1.21, which led to my misjudgment

This is machine translation. My English is not very good, please understand

### Steps to Reproduce

no

### Minecraft version

1.21

### Game Logs

no

### Additional Information

no

**Comment by Exopandora** [comment]
Please provide the logs. I'm assuming that you are having a compatibility issue with another mod. Minecraft version 1.21.1 and 1.21 are nearly identical, besides a singular crash fix, that should not affect mod compatibility in any way.

**Comment by Shizoukia** [comment]
> Please provide the logs. I'm assuming that you are having a compatibility issue with another mod. Minecraft version 1.21.1 and 1.21 are nearly identical, besides a singular crash fix, that should not affect mod compatibility in any way.

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-09-26 05:10:43
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'shouldersurfing'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110)
	at oolloo.jlw.Wrapper.main(Wrapper.java:103)
Caused by: java.lang.NoSuchMethodError: 'net.neoforged.neoforge.common.ModConfigSpec$Builder net.neoforged.neoforge.common.ModConfigSpec$Builder.gameRestart()'
	at com.github.exopandora.shouldersurfing.config.Config$ClientConfig.<init>(Config.java:423)
	at net.neoforged.neoforge.common.ModConfigSpec$Builder.configure(ModConfigSpec.java:763)
	at com.github.exopandora.shouldersurfing.config.Config.<clinit>(Config.java:36)
	at com.github.exopandora.shouldersurfing.fabric.ShoulderSurfingFabric.onInitializeClient(ShoulderSurfingFabric.java:19)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
```

*But I used version 1.21 of the mod and it won't crash. I used the latest mod version, which caused this crash, but if I use the last version of 1.21, it won't crash*

**Comment by Exopandora** [comment]
I'm guessing that you are using an outdated version of forge config api port. But I can't tell without the **full** crash log.

**Comment by Shizoukia** [comment]
> I'm guessing that you are using an outdated version of forge config api port. But I can't tell without the **full** crash log.

I am using the final forget config API of version 1.21

This is the complete log, and I think it may still be a version compatibility issue

Anyway, I suggest you remove the 1.21 version jar from the 1.21 version. However, there are still some differences between the two versions
Even if it's not an issue with your mod, it could still be a problem with the library. Your mod is backward compatible with 1.21, but the library mod may not be compatible

```
I am using the final forget config API of version 1.21

This is the complete log, and I think it may still be a version compatibility issue

Anyway, I suggest you remove the 1.21 version jar from the 1.21 version. However, there are still some differences between the two versions
Even if it's not an issue with your mod, it could still be a problem with the library. Your mod is backward compatible with 1.21, but the library mod may not be compatible
```

**Comment by Exopandora** [comment]
You only have forge config api port installed via a bundled dependency from "Yes Steve Model". The bundled version of forge config api port is 21.0.0, which is far older than the latest version (21.0.8). Please place forge config api port version 21.0.8 in your mods folder.

**Comment by Shizoukia** [comment]
> You only have forge config api port installed via a bundled dependency from "Yes Steve Model". The bundled version of forge config api port is 21.0.0, which is far older than the latest version (21.0.8). Please place forge config api port version 21.0.8 in your mods folder.

Okay, thank you, but I don't plan on uninstalling this mod at the moment because the compatible version supported by my client is that one
Currently, I have not encountered any problems using the old version of ShoulderSurfing

I'm just suggesting the tag issue in curseforge for version 1.21

Thank you for your help. Wishing you a pleasant day

**Comment by Exopandora** [comment]
I'm not telling you to uninstall "Yes Steve Model". You simply need to add the latest version of forge config api port to your mods list.

**Comment by Exopandora** [comment]
Anyways, thanks for reaching out!

**Comment by Shizoukia** [comment]
> I'm not telling you to uninstall "Yes Steve Model". You simply need to add the latest version of forge config api port to your mods list.

uh, ik that, I mean is that there may not be a need to update to the latest version for compatibility at the moment
At present, all mods are basically stable, so I don't plan to use them to avoid compatibility issues caused by other mods

*After all, I am not currently using the latest Minecraft. Thank you for your reply: D*
