### ISSUE TITLE
Disabling front view crosshair only 

### ISSUE THREAD

**Issue by EzerArch** [Exopandora/ShoulderSurfing#25]
Hello, I'm a... hm... a longtime user of Shoulder Surfing and I'm back using it. :)

Is there a way to disable the front view crosshair without disabling the third person one? In the following 2014 video, you see the crosshair is visible on third person camera but it's hidden on front view: https://youtu.be/fEUZd3gcvew?t=61.

It feels like there's a bug on my face (and why would I aim at my own face btw?). The only way I've found to disable it was to set `Third Person Crosshair` to `false`, then I miss it on third person camera. Set `Third Person Crosshair` back to `true` and I have the crosshair showing on both front view and third person camera.

![2020-06-26_11 36 04](https://user-images.githubusercontent.com/6743303/86098354-602d7100-ba8c-11ea-8472-f04c9d5c23bb.png)

![2020-06-26_11 36 14](https://user-images.githubusercontent.com/6743303/86098371-64f22500-ba8c-11ea-8a91-04a0d04a5fdb.png)

Regards, 

(EDIT: fixed. Redone a lost edit)

**Comment by Exopandora** [comment]
You can now set the crosshair visibility for each perspective individually
