### ISSUE TITLE
Crash when changing persectives.

### ISSUE THREAD

**Issue by IsNotLana** [Exopandora/ShoulderSurfing#253]
### Description

Seems to crash randomly when pressing the perspective swap key [F5]

### Steps to Reproduce

1. Press F5 repeatably until it crashes. Seems to be random, could take a only a few, could take ALOT.

### Minecraft version

1.21.1

### Game Logs

https://mclo.gs/hsmfIRh

**Comment by Exopandora** [comment]
Thanks for reporting, A new version containing a fix will be available for download soon.
