### ISSUE TITLE
Incompatible with Starminer

### ISSUE THREAD

**Issue by branman5949** [Exopandora/ShoulderSurfing#254]
### Description

when the mod "Starminer" is present the Shoulder Surfer camera no longer works at all and I was wondering if you could fix this in 1.7.10 minecraft
https://www.curseforge.com/minecraft/mc-mods/star-miner/files/3151097

### Minecraft version

1.7.10

### Incompatible mod name

StarMiner

### Incompatible mod version

1.0

### Game Logs

https://mclo.gs/k9IaTU0

**Comment by branman5949** [comment]
trying out the shoulder surfer but i can't move the shoulder camera anywhere and its stuck in the middle.
https://github.com/user-attachments/assets/4a8375ad-15af-46ca-afcd-aa57f5068f91

**Comment by Exopandora** [comment]
Sorry, but Minecraft version 1.7.10 is no longer supported.
