### ISSUE TITLE
Camera doesn't rotate with spectated players 

### ISSUE THREAD

**Issue by n-aspen** [Exopandora/ShoulderSurfing#255]
### Description

When a spectator uses the shoulder surfing perspective and spectates a player their camera doesn't follow the spectated player's rotation, even when the camera otherwise would outside of spectator mode. 

### Steps to Reproduce

1. Use the default settings, but *disable* **"Camera"** -> **"Decouple Camera"**.
2. Confirm that the camera rotates with the player.  
3. Spectate another player while in the shoulder surfing perspective.  
4. Rotate the spectated player to see that the camera is acting as if it were decoupled. 

### Minecraft version

1.21.3

### Game Logs

https://mclo.gs/0xLxmFV

**Comment by Exopandora** [comment]
Thank you for reporting. This is indeed an oversight and will be fixed in the next version, which will be released later today.

**Comment by n-aspen** [comment]
Thank you so much! <3
