### ISSUE TITLE
Epic fight lock on broken in 1.20.1

### ISSUE THREAD

**Issue by ClixzyFN** [Exopandora/ShoulderSurfing#258]
### Description

when i use lock on when using epic fight camera breaks and disconnects from player and movement is broken unless i unlock on

### Minecraft version

1.20.1

### Incompatible mod name

Epic Fight

### Incompatible mod version

20.9.6

### Game Logs

https://mclo.gs/eVyJOhz

**Comment by ClixzyFN** [comment]
https://github.com/user-attachments/assets/e898c3a8-5549-4f20-9289-dd6a928f9891

**Comment by Exopandora** [comment]
Thanks for reporting. The bug has been fixed and a new version will be available for download very soon.

**Comment by ClixzyFN** [comment]
> Thanks for reporting. The bug has been fixed and a new version will be available for download very soon.

is it out im kinda late
