### ISSUE TITLE
[1.16.2] Missing license exception

### ISSUE THREAD

**Issue by voiddog** [Exopandora/ShoulderSurfing#27]
In 1.16.2 a license inside a mod is being enforce.
https://github.com/MinecraftForge/MinecraftForge/pull/7241

**Comment by Exopandora** [comment]
As it says on the curseforge download this mod is for 1.16.1 and not 1.16.2. Due to changes made by mojang this mod is currently incompatible with 1.16.2 and im still waiting on features by forge.
