### ISSUE TITLE
[1.12.2] When i download the 1.12.2  (and older versions)  its just says ''failed - no files.

### ISSUE THREAD

**Issue by Zignomitos** [Exopandora/ShoulderSurfing#28]
someone help me, i want to play with this mod ,-,

**Comment by Exopandora** [comment]
Compiled versiosn are available on curseforge and there is nothing i can do about their service availability. You can use the following list to download 1.12.2 versions:
https://www.curseforge.com/minecraft/mc-mods/shoulder-surfing-reloaded/files/all?filter-status=1&filter-game-version=2020709689%3A6756
