### ISSUE TITLE
The next point of view can only be shifted 1.12.2

### ISSUE THREAD

**Issue by ainlzj** [Exopandora/ShoulderSurfing#30]
The next point of view can only be shifted
1.12.2

**Comment by Exopandora** [comment]
Could you explain that a little more in detail?

**Comment by ainlzj** [comment]
That is, when you move the perspective, you need to click a little bit to change the perspective

**Comment by ainlzj** [comment]
The angle of view can change infinitely as long as you press it all the time
And then I kept pressing, it could only be changed

**Comment by ainlzj** [comment]
![image](https://user-images.githubusercontent.com/66135518/100898271-8b186700-34fb-11eb-9dd5-e3eea2325e6e.png)
This is infinite change. The perspective keeps pressing and moving
My perspective, however, has changed only a little

**Comment by Exopandora** [comment]
You do mean:
1. You cannot hold down the buttons to ajust the perspective and therefor have to press multiple times.
2. The camera adjustment stops at a certain point

**Comment by ainlzj** [comment]
YES

**Comment by Exopandora** [comment]
Do you mean both **or** 1 **or** 2 ?

**Comment by ainlzj** [comment]
1

**Comment by Exopandora** [comment]
Well the 1.12.2 versions of forge are end of support. Due to this i am unable to change the mod in any way.

**Comment by ainlzj** [comment]
OK
