### ISSUE TITLE
Crash on world creation or loading into the world

### ISSUE THREAD

**Issue by SouthernPixel** [Exopandora/ShoulderSurfing#31]
https://paste.gg/p/anonymous/5be8243d9d7243a2b1bb200f8a9199aa There is the crash report. Should I provide the debug.log as well?

**Comment by Exopandora** [comment]
The issue seems to be caused by another mod in relation to optifine (but according to the crashlog you do not have optifine installed). It would be very helpful if you could isolate the mod that causes the issue so i can potentially fix it.

**Comment by SouthernPixel** [comment]
Um, im not sure how I could do that, i have like 100 something mods

**Comment by Exopandora** [comment]
The easiest method would be to split the list in half and figure out in which half the crash occurs. If you found the half, repeat the method again until you know which mod causes the issue.

**Comment by Exopandora** [comment]
Other people seem to encounter this issue. Did you find out which mod(s) caused the issue?
