### ISSUE TITLE
[Suggestion] Draw outline for entities hidden by the player model

### ISSUE THREAD

**Issue by xelotex** [Exopandora/ShoulderSurfing#35]
¿what about aplaying glowing to mobs that are in the middle of the player when in third person?, that way you can always keep it the track, or you can make the player a bit transparent, this are some mechanics that i have seen in some third person games.

here's a image of what i'm talking about:
![2021-02-22_10 45 31](https://user-images.githubusercontent.com/70168682/108740689-8dd39880-74fb-11eb-87a2-d57520be6e8b.png)

**Comment by Exopandora** [comment]
I get the point but i dont know if the rendering engine is capable of such a feature.

**Comment by xelotex** [comment]
what do you mean with "if the rendering engine is capable of such a feature"? do you mean that it could cause lag? ¿or that the minecraft engine can't do that? if is the second thing minecraft already has a potion effect that applies a glowing effect, so you need to make that every time the player can't see a mob because it is in front of the player model, the mod will automatically apply glowing to it continually until the mob moves, maybe make the player transparent would be more effective but the vanilla engine probably isn't capable of that, that's what you're meaning right? if yes then you could go for the glowing option if you want.
