### ISSUE TITLE
audio in my left ear

### ISSUE THREAD

**Issue by Fahobomoclowbia** [Exopandora/ShoulderSurfing#36]
since the player is further to the left with this mod, all the audio for the player like walking and stuff is in my left ear. i feel like this is not how it is supposed to be. i do have optifine installed if it makes a difference.

**Comment by Exopandora** [comment]
Please swap the shoulde (press 'o') and report back if the audio is still coming just from the left

**Comment by Fahobomoclowbia** [comment]
> Please swap the shoulde (press 'o') and report back if the audio is still coming just from the left

When I swap shoulders to the right, the audio only comes from the right.

**Comment by Exopandora** [comment]
Maybe its because of optifine or some other mod. Please make sure this issue occurs with only shoulder surfing installed.

**Comment by Fahobomoclowbia** [comment]
> Maybe its because of optifine or some other mod. Please make sure this issue occurs with only shoulder surfing installed.

It must be optifine, because this is a fresh install and optifine is the only other mod I have

**Comment by Exopandora** [comment]
So if its confirmed caused by optifine, please open up an issue over there as there is nothing i can do about it. Rendering should have nothing to do with sound

**Comment by Fahobomoclowbia** [comment]
alright thanks
