### ISSUE TITLE
Keys registering

### ISSUE THREAD

**Issue by LoganInf1** [Exopandora/ShoulderSurfing#37]
When I initially got the mod it sometimes actually moved to the camera when I press the keys, but for some reason it stopped doing anything when I pressed the keys, I'm not sure what happened. But its happening a lot and if it can't even register like this the mod is useless to me. For example I is to zoom out but when you press I it doesn't zoom out

**Comment by Exopandora** [comment]
Please provide the resulting crash log from pressing F3 +C for 10 seconds while ingame. This issue may be related to #33
