### ISSUE TITLE
Bow trajectory no longer working?

### ISSUE THREAD

**Issue by zaxxstar** [Exopandora/ShoulderSurfing#39]
So I was using this mod, and whenever I was firing a bow, I saw a trajectory of where my arrow was gonna fly. Now, that seems to be turned off though, and even after reinstalling the mod, there's still no trajectory.

Am I crazy? Was this not a part of the mod? Was something else causing this?

**Comment by Exopandora** [comment]
You probably just turned off particles in your graphics settings as this mod changes nothing about the bow graphics in any way.
