### ISSUE TITLE
Distance Question

### ISSUE THREAD

**Issue by DrMystic03** [Exopandora/ShoulderSurfing#41]
I've just got a question on how I would make it so I can go further out from my character, in 1.14.4 which I've been using for a while I am able to go nearly as far out as I want but I can't seem to get the same with 1.16.5. Im probably just reading the config file wrong honestly.

**Comment by Exopandora** [comment]
You need to adjust the following settings in `shouldersurfing.toml`:

You can specify a custom min or max value for the camera offset:
```
[perspective.offset.min]
	#If x-offset is limited this is the minimum amount
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min_offset_x = -3.0
	#If z-offset is limited this is the minimum amount
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min_offset_z = -3.0
	#If y-offset is limited this is the minimum amount
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	min_offset_y = -1.0

[perspective.offset.max]
	#If z-offset is limited this is the maximum amount
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max_offset_z = 5.0
	#If y-offset is limited this is the maximum amount
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max_offset_y = 1.5
	#If x-offset is limited this is the maximum amount
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	max_offset_x = 3.0
```

Or you can disable limit alltogether:
```
[perspective.offset.limits]
	#Whether or not z-offset adjustment has limits
	unlimited_offset_z = false
	#Whether or not y-offset adjustment has limits
	unlimited_offset_y = false
	#Whether or not x-offset adjustment has limits
	unlimited_offset_x = false
```

Note that you need to edit the lines without the preceeding `#`

**Comment by DrMystic03** [comment]
[perspective]
	#Whether or not to replace the default third person perspective
	replace_default_perspective = false
	#Size of the camera adjustment per step
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	camera_step_size = 0.05
	#Whether or not to hide the player model if the camera gets too close to it
	keep_camera_out_of_head = true
	#Whether or not to limit the player reach depending on the crosshair location (perspective offset)
	limit_player_reach = true
	#The default perspective when you load the game
	#Allowed Values: FIRST_PERSON, THIRD_PERSON_BACK, THIRD_PERSON_FRONT, SHOULDER_SURFING
	default_perspective = "FIRST_PERSON"
	#Whether or not to remember the last perspective used
	remember_last_perspective = true

	[perspective.offset]
		#Third person camera x-offset
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		offset_x = -3.8163916471489756E-16
		#Third person camera y-offset
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		offset_y = 0.0
		#Third person camera z-offset
		#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
		offset_z = 5.0

		[perspective.offset.min]
			#If x-offset is limited this is the minimum amount
			#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
			min_offset_x = -3.0
			#If z-offset is limited this is the minimum amount
			#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
			min_offset_z = -3.0
			#If y-offset is limited this is the minimum amount
			#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
			min_offset_y = -1.0

		[perspective.offset.max]
			#If z-offset is limited this is the maximum amount
			#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
			max_offset_z = 5.0
			#If y-offset is limited this is the maximum amount
			#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
			max_offset_y = 1.5
			#If x-offset is limited this is the maximum amount
			#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
			max_offset_x = 3.0

		[perspective.offset.limits]
			#Whether or not z-offset adjustment has limits
			unlimited_offset_z = false
			#Whether or not y-offset adjustment has limits
			unlimited_offset_y = false
			#Whether or not x-offset adjustment has limits
			unlimited_offset_x = false

[crosshair]
	#Whether or not to show the crosshairs farther than normal
	show_crosshair_farther = true
	#Crosshair type to use for shoulder surfing
	#Allowed Values: ADAPTIVE, DYNAMIC, STATIC, STATIC_WITH_1PP
	crosshair_type = "ADAPTIVE"

	[crosshair.visibility]
		#Crosshair visibility for first_person
		#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
		first_person = "ALWAYS"
		#Crosshair visibility for shoulder_surfing
		#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
		shoulder_surfing = "ALWAYS"
		#Crosshair visibility for third_person_back
		#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
		third_person_back = "NEVER"
		#Crosshair visibility for third_person_front
		#Allowed Values: ALWAYS, NEVER, WHEN_AIMING, WHEN_IN_RANGE, WHEN_AIMING_OR_IN_RANGE
		third_person_front = "NEVER"

This is what I've got for my config but this is as far as I can get it to go 
![image](https://user-images.githubusercontent.com/68919699/115123459-241bbc00-9f8b-11eb-95d7-207fdc969ba5.png)

**Comment by Exopandora** [comment]
This is the section to disable offset limits for the respective dimensions
```
[perspective.offset.limits]
		#Whether or not z-offset adjustment has limits
		unlimited_offset_z = false
		#Whether or not y-offset adjustment has limits
		unlimited_offset_y = false
		#Whether or not x-offset adjustment has limits
		unlimited_offset_x = false
```

For example if you set `unlimited_offset_z = false` to `unlimited_offset_z = true` you can set the camera as far back as you want.
If you set `unlimited_offset_y = false` to `unlimited_offset_y = true` you can set the camera as high as you want. (`unlimited_offset_x` for left/right).

You can also specify a limit for each offset as i said in the first block in my first comment. Just set i.e. `max_offset_z = 5.0` to `max_offset_z = 10.0`. This allows you to set the camera back 10 blocks instead of just 5.

**Comment by DrMystic03** [comment]
Ahhh I gotcha! Problem solved :)
