### ISSUE TITLE
Crosshair Bobbing With Ranged Weapons

### ISSUE THREAD

**Issue by fogoplayer** [Exopandora/ShoulderSurfing#43]
When using ranged weapons like the bow or the trident, the crosshair drifts towards the player, and then bobs and weaves onscreen as the player looks around.

Observed on Minecraft 1.16.5, Forge 36.1.0, Shoulder Surfing 2.0.3

**Comment by Exopandora** [comment]
This is intentional and accurately displays where you actually aim at with the weapon

**Comment by Exopandora** [comment]
If you do not want this behaviour you can set `crosshair` -> `crosshair_type` from `ADAPTIVE` to `STATIC` in file `.../.minecraft/config/shouldersurfing.toml`. But when you do this you will no longer get an accurate preview on where your arrows will hit the ground.

**Comment by fogoplayer** [comment]
Ok, thanks for explaining!
