### ISSUE TITLE
[Bug] Doors don't open when interacted with in the shoulder surfing perspective

### ISSUE THREAD

**Issue by Corvus20** [Exopandora/ShoulderSurfing#48]
This sounds absurd I know, but right clicking the doors while in this perspective makes the sound play but the door doesnt open. It isn't some sort of rendering glitch, they are actually still closed. Going into normal first person or third person and right clicking a door works just fine, however.

**Comment by Exopandora** [comment]
1.16?

**Comment by Exopandora** [comment]
Please provide the resulting crash log from pressing `F3` + `C` for 10 seconds while ingame.

**Comment by DylanCordoza** [comment]
I'm having a similar issue, got a lot of other mods loaded though so idk how helpful the log will be :p
[crash-2021-06-04_11.13.25-client.txt](https://github.com/Exopandora/ShoulderSurfing/files/6600494/crash-2021-06-04_11.13.25-client.txt)

**Comment by Gamirosh** [comment]
Got a similar issue, however I got a lot of other mods running so idk how helpful the log will be :p.
[crash-2021-06-04_11.13.25-client.txt](https://github.com/Exopandora/ShoulderSurfing/files/6600515/crash-2021-06-04_11.13.25-client.txt)

**Comment by Exopandora** [comment]
Yeah this issue is likely caused by another mod installed alongside shoulder surfing. The easiest method would be to split the list in half and figure out in which half the crash occurs. If you found the half, repeat the method again until you know which mod causes the issue. This would greatly speedup a potential fix.

**Comment by Gamirosh** [comment]
Found it, conflict seems to be with the better third person mod: https://www.curseforge.com/minecraft/mc-mods/better-third-person

**Comment by Exopandora** [comment]
Nice! I will look into it in the next few days and see what i can do.

**Comment by Gamirosh** [comment]
many thanks :D!

**Comment by Exopandora** [comment]
So i did some further testing and for it turned out to be an issue of Better Thrid Person itself. If you only install that mod doors will not open properly. It has nothing to do with shoulder surfing.

**Comment by Exopandora** [comment]
Turns out this is a known issue: https://www.curseforge.com/minecraft/mc-mods/better-third-person/issues/11
