### ISSUE TITLE
Long-range weapon sights of other modules are invalid

### ISSUE THREAD

**Issue by dajiuji** [Exopandora/ShoulderSurfing#50]
When using a bow or crossbow in the over-the-shoulder perspective (I did not try the trident), the crosshair will adapt and aim, but it does not have such an effect on the ranged weapons of other mods.
For example: MrCrayfish's gun
version : 1.16.5
Forge : 36.1.25
mod : ShoulderSurfing-2.0.3.jar
Oh, I just found out that there is a new version. Is this resolved in the new version? I'll try it later.

**Comment by Exopandora** [comment]
This should not be resolved in newer versions but it should adapt the crosshair when a modded weapon uses certain properties (pull, throwing, charged). I could add a list as a config option for items that you want the adaptive crosshair on.
