### ISSUE TITLE
[1.12.2-2.1] Crash/Stall before MC window appear

### ISSUE THREAD

**Issue by Krutoy242** [Exopandora/ShoulderSurfing#51]
New version 1.12.2-2.1 caused MC client stall at first seconds of lunching: application appears in Task Manager, but Java window not appear.
Still, Java process is running, consuming about 1GB of memory, but nothing changes for minutes.

[debug.log](https://github.com/Exopandora/ShoulderSurfing/files/6707012/debug-2.log.gz)

**Comment by Exopandora** [comment]
Looks like an incompatibility issue with Astral Sorcery. I will fix that later

**Comment by Exopandora** [comment]
A new version is planned for tomorrow if all tests pass
