### ISSUE TITLE
[1.16.5] Game freezes indefinitely after some time with modified 3rd person

### ISSUE THREAD

**Issue by LapizGaming7751** [Exopandora/ShoulderSurfing#54]
Mods: 
> Better Third Person
> Better Title Screen
> CraftPresence
> [Ears](https://www.curseforge.com/minecraft/mc-mods/ears) 
> Jade
> JEI
> Optifine
> Smoothboot

Shader used: Sildurs Vibrant Shaders v1.29 Medium
Resource Packs:
> Clarity
> Dark Smooth GUI

**Comment by Exopandora** [comment]
Are you sure that this only happens if shoulder surfing is installed?

**Comment by LapizGaming7751** [comment]
Well I'm not so sure anymore.. Rn I'm looking for fixes

**Comment by LapizGaming7751** [comment]
Ah, no worries now, turns out it's one of the shaders I have. I'm all alright now
