### ISSUE TITLE
[1.16.5] GUI is shifted when using dynamic crosshair

### ISSUE THREAD

**Issue by evanbones** [Exopandora/ShoulderSurfing#55]
When you open a chest with the dynamic crosshair
![2021-07-27_05 19 33](https://user-images.githubusercontent.com/74276616/127152526-ae1f6381-fce8-4ffc-962d-a66e91575a8a.png)

When you open your inventory with the dynamic crosshair
![image](https://user-images.githubusercontent.com/74276616/127152168-ad8e4ea4-b600-4e08-b0fb-58d0812f58fc.png)

I have a basic understanding of why this could happen, because presumably the crosshair is connected to the normally stationary gui position, and when it moves, the gui moves with it

**Comment by Exopandora** [comment]
Are you using optifine?

**Comment by evanbones** [comment]
No, but I am using Sodium Reforged. Let me test without it

**Comment by evanbones** [comment]
Yep, still happens even without Sodium. I'll try a clean install with just Should Surfing as well

**Comment by Exopandora** [comment]
I tested it with "clean" ssr and the issue does not appear

**Comment by evanbones** [comment]
It's probably a compatability issue then. I'll run some more tests

**Comment by evanbones** [comment]
Ah ha, it was a compatability issue with Console Experience. I'm betting it was the floating hotbar that did it. Thanks!
