### ISSUE TITLE
Broken camera with the Immersive Portals mod for Forge 1.16.5

### ISSUE THREAD

**Issue by MysticTerror394** [Exopandora/ShoulderSurfing#56]
When i go into shoulder surf mode and then walk up to a portal with the Immersive Portals Mod it is all glitchy and buggy/broken. It works fine with the other camera modes until you change to third person shoulder. Can you please fix this? Here is a clip of the problem:

https://user-images.githubusercontent.com/70053800/128681117-0f3bb4fe-4e9a-426a-ac93-45404b715f2f.mp4

**Comment by Exopandora** [comment]
Immersive Portals does not respect camera position changes made by forge events. This makes it an issue for Immersive Portals and not ssr as there is nothing i can do about it.
