### ISSUE TITLE
Not the right block is mined

### ISSUE THREAD

**Issue by DcNdrew** [Exopandora/ShoulderSurfing#59]
I think the picture says everything.
ShoulderSurfing-1.16.5-2.2.1.jar

![2021-08-15_05 33 55](https://user-images.githubusercontent.com/9825888/129466197-b9fe4d38-e779-4fb4-9bb3-ac0ab98cb076.png)

**Comment by Exopandora** [comment]
This is intentional. Otherwise you would not see which block you are mining.
