### ISSUE TITLE
[Slight Issue]

### ISSUE THREAD

**Issue by ModernSilver** [Exopandora/ShoulderSurfing#6]
Hello, thought I'd say that I love your mod, just a slight issue I noticed.

I'm using the version on Curse forge, and the config, at default, is set to render the player model invisible when the camera gets too close. It does that just fine, however it also renders all other players invisible as well. I checked the version here on Github as well and it appears to do the same thing.

I'd appreciate a possible fix to this if possible.

**Comment by Exopandora** [comment]
Thanks for the report!
The issue will be fixed for version 1.12.2-1.13

**Comment by ModernSilver** [comment]
Wow, that was fast.

Thanks for looking into that!
