### ISSUE TITLE
1.8.9 update needed

### ISSUE THREAD

**Issue by SosigDOGGO** [Exopandora/ShoulderSurfing#60]
i use 1.8.9 for Hypixel skyblock and shoulder surfing is one of my favorite mods, i downloaded the 1.8.9 version, booted it up, and it worked(kinda) the camera was not offset and i could not figure out how to offset the camera ( i tried using the arrow keys the did not work) please fix the issue so i can use your amazing mod!

**Comment by Exopandora** [comment]
Is there really no way to use a newer version of the game? If so what other mods are you using? Please provide the launcher log of the game otherwise there is no way for me to even remotely fix this.

**Comment by SosigDOGGO** [comment]
im using skyblock addons(1.8.9 ver 1.5.5) optifine(newest) and inventory hud, can we further discuss this privately on discord? (my username is !DOGGO!#3300 ill send the logs there

**Comment by SosigDOGGO** [comment]
the reason im playing on 1.8.9 is because the skyblock addons mod only supports 1.8.9

**Comment by Exopandora** [comment]
Just put the logs up on pastebin or gist.github.com

**Comment by SosigDOGGO** [comment]
is drive okay too?

**Comment by Exopandora** [comment]
sure

**Comment by SosigDOGGO** [comment]
https://drive.google.com/file/d/1rWdfFC38QTBE9CUNphu9incsiq2WghNX/view?usp=sharing

**Comment by SosigDOGGO** [comment]
the arrow keys do nothing just like the pg up and pg down

**Comment by Exopandora** [comment]
is there also a `debug.log` ?

**Comment by SosigDOGGO** [comment]
one sec

**Comment by SosigDOGGO** [comment]
no there is not

**Comment by SosigDOGGO** [comment]
can you maybe remake the mod?

**Comment by Exopandora** [comment]
i will take a look at how easy the current 1.12 version is to backport

**Comment by SosigDOGGO** [comment]
ok, thanks!

**Comment by SosigDOGGO** [comment]
i really like your mod and i use it every day on 1.16.5 either way thanks for your work!

**Comment by SosigDOGGO** [comment]
also the 1.7.10 version works correctly i tried it before
