### ISSUE TITLE
[BUG] [1.7.10] Keybinds don't work

### ISSUE THREAD

**Issue by MagmaSlime123** [Exopandora/ShoulderSurfing#65]
**Describe the bug**
Title.

**To Reproduce**
Use the camorra movement kerybinds.

**Expected behavior**
Them to work.

**Screenshots**
N/A

**Crashlogs**
N/A

**Other mods**
N/A

**Additional information**
N/A

**Comment by MagmaBro123** [comment]
Yes, 1.7.10. And no.
