### ISSUE TITLE
[BUG] [1.12] Inventory/chat player visibility when against a wall

### ISSUE THREAD

**Issue by mjaske** [Exopandora/ShoulderSurfing#67]
When Shoulder Surfing, if you have your back against a wall, it automatically hides your player to allow for better vision, a fantastic feature. However, if you then are in your inventory or typing in chat, your player becomes visible again. This is irritating if you want to see when organising pots/food in your inventory mid fight and you are in a corner or something.

To reproduce simply go into Shoulder Surfing mode from behind the player and back up to a wall. Press E or T.

Bug occurs with latest version of Shoulder Surfing in Minecraft 1.12.

**Comment by Exopandora** [comment]
I dont see a reason to make this a config option but you can do it on your own as follows:

### Prerequisites ###
1. Install Java 8 Development Kit  and add it to the PATH environment variable
2. Install git

### Build ###
Open a terminal and run the following commands:
1. `https://github.com/Exopandora/ShoulderSurfing.git`
2. `cd ShoulderSurfing`
3. `git checkout 1.12.2`
4. Remove `&& Minecraft.getMinecraft().currentScreen == null` from line 58 in `src/main/java/com/teamderpy/shouldersurfing/event/ClientEventHandler.java`
5. Linux: `gradlew build`
Windows:`gradlew.bat build`

You may have to run `gradlew setupDecompWorkspace` before the last command.
