### ISSUE TITLE
[Suggestion] [Dynamic Surfing] [1.16.5] Camera only goes over shoulder when weapon equipped

### ISSUE THREAD

**Issue by heaganhenry** [Exopandora/ShoulderSurfing#68]
Dynamic Surfing:
Can you add an optional feature that keeps the camera directly behind the player until a weapon/tool is equipped. The camera should pan smoothly to the side and back when equipping/unequipping said item.

Auto Side Swap:
Instead of using the hotkey have the camera switch sides based on player movement. When walking to the left the camera should auto pan to the right, and vice versa. When walking to the right the camera should auto pan to the left. As seen here https://www.youtube.com/watch?v=ODIDV75yWIE

**Comment by Exopandora** [comment]
Sorry for the very late reply, I just saw this while going through all open issues. First of all, thanks for the suggestion. After some consideration, I came to the conclustion that this is a nice idea, but in a game like Minecraft, you want to easily place blocks. In the linked video, you can see that the player is moving left and right, but the crosshair position is not moving with them. This would make it really hard for the player to place any blocks. So while I get the idea, I do not think that it contributes towards a good user experience.
