### ISSUE TITLE
[FEATURE] [1.12] STATIC_WITH_1PP compat with Vic's Modern Warfare

### ISSUE THREAD

**Issue by CitrusHappy** [Exopandora/ShoulderSurfing#69]
Currently, there is an array in place to whitelist all items that a modpack developer would want to force the player into first-person mode if they are holding said item.

I am requesting another array that makes an item function similar to the bow and arrow, where it will force the player into first-person mode only if they AIM down sights. Specifically for the mod Vic's Modern Warfare.

This could be a more mod inclusive system though, making it so only if right-click is detected and the item is held, it will force a perspective change. (maybe make it possible to switch back to a third-person perspective like a toggle?)

**Comment by Exopandora** [comment]
Technically this system should already work with mods if the item has certain properties. Those include pulling and throwing. If a mod author adds these properties to their item it will automatically work.

**Comment by CitrusHappy** [comment]
Yeah like modded bows work since they already use vanilla bow properties. It seems that Vics uses none of those properties. So maybe a way to check for the property they use, and then there will be no need for another array?

**Comment by Exopandora** [comment]
Well yes, but the mod is closed source anyway. Without additional tools you will not figure out the name of the property. But can you give me the name of the item you want this mechanic to work on?

**Comment by CitrusHappy** [comment]
Ideally any guns from this mod, but how about the mw:colt_m45a1 item. I will see if I can find the name of the property.

**Comment by Exopandora** [comment]
I already took a glimpse at the code and there are no properties.

**Comment by CitrusHappy** [comment]
Looks like the current array is the only viable method of auto first person, I will try to contact the creators of Vics in order to add a property that makes this possible.
