### ISSUE TITLE
[BUG] [1.17] No crosshair in 1.17

### ISSUE THREAD

**Issue by SakuranoKagura** [Exopandora/ShoulderSurfing#70]
Hello, I found there's no crosshair for 1.17, it was fine when I played 1.16.5 before, thanks.

**Comment by Exopandora** [comment]
Please fill in all the details from the [issue template](https://github.com/Exopandora/ShoulderSurfing/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Exopandora** [comment]
Issue closed due to no further information provided
