### ISSUE TITLE
[BUG] [1.7.10 (I know. Old, but still used.] Crashes when around an LOTR Oddment Collector.

### ISSUE THREAD

**Issue by MagmaBro123** [Exopandora/ShoulderSurfing#71]
**Describe the bug**
Title.

**To Reproduce**
Install the Lord of The Rings mod along with Shoulder Surfing. Login to a world or server, and either find or spawn an Oddment Collector.

**Expected behavior**
The game not crashing.

**Screenshots**
N/A

**Logs**
https://pastebin.com/qwQfuUPp

**Other mods**
See the crash report. Easily reproduceable, even without the listed mods.

**Additional information**
I know 1.7.10 is very old at this point, but people do still use it, and it is still quite famous, apparently.

**Comment by Exopandora** [comment]
Does it also crash with ShoulderSurfing-1.7.10-2.2.2 ?

**Comment by MagmaBro123** [comment]
I was using 2.2.3. So, yes.

**Comment by Exopandora** [comment]
Yes, but does it also crash with ShoulderSurfing-1.7.10-2.2.2 ?

**Comment by MagmaBro123** [comment]
Sorry for the VERY late response.

Both .2 and 3 will cause the same crash.

**Comment by Exopandora** [comment]
Turns out the mcp guys archived their work and you can no longer create workspaces for 1.11 and below (at least to my knowledge). Until there is a way to get it working anyways i am no longer able to provide any support for this version. Source: https://twitter.com/bspkrs/status/1461778190574174210

**Comment by MagmaBro123** [comment]
Ugh...

**Comment by Exopandora** [comment]
I'm closing this now. Feel free to reopen this issue when [RetroGradle](https://github.com/RetroGradle/ForgeGradle/) has been ported to 1.7.10.

**Comment by Exopandora** [comment]
Short update: I got a functional development workspace now but the game does not crash when spawning an oddment collector with the version numbers provided.

**Comment by MagmaBro123** [comment]
Huh...

**Comment by Exopandora** [comment]
![SSR+LotR](https://user-images.githubusercontent.com/18708736/195996083-9831b87a-64bb-490d-b4e2-abdc6b3b16c5.png)

**Comment by MagmaBro123** [comment]
Something must've fixed it apparently.

**Comment by Exopandora** [comment]
But i used the same old version

**Comment by MagmaBro123** [comment]
Huh.

**Comment by Exopandora** [comment]
If the issue persists on your side, feel free to reopen this issue.
