### ISSUE TITLE
[BUG] [1.12.2] Not compatible with Better Third Person

### ISSUE THREAD

**Issue by 3axleb** [Exopandora/ShoulderSurfing#72]
**Describe the bug**
When i rotate camera with mod "Better Third Person", camera goes through blocks and causes x-ray in small rooms.

**Expected behavior**
Don't see through blocks.

**Other mods**
Better Third Person: https://www.curseforge.com/minecraft/mc-mods/better-third-person/issues

**Logs**
[latest.log](https://github.com/Exopandora/ShoulderSurfing/files/8128741/latest.log)

**Screenshot**
![2022-02-24_06 21 18](https://user-images.githubusercontent.com/100180164/155433314-5278daaf-9cea-4f44-8cab-f4a634216624.png)

**Comment by Aeron216** [comment]
I can confirm that this happens with the latest version, 2.2.1.

Try with 1.15.1 from April 23rd 2019. It doesn't seem to have this issue. Worth the downgrade imo, x-rays on demand are a little gamebreaking.
