### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by asianfry** [Exopandora/ShoulderSurfing#73]
Hi, I am unsure of why my game does not let me control the camera! I'm on 1.18.1, I tried reassigning keybinds, that did not work, and removing and reinstalling the mod. What makes it even weirder is that a friend also downloaded the mod and has the same exact mods I have and it works for them. Only difference is that I'm on windows and theyre on mac

edit- never mind i am stupid, i needed to go to some, fourth perspective? after pressing F5 a bunch i came to the new shoulder surfed one

**Comment by Exopandora** [comment]
Glad you figured that out. You can also enable the option to replace the default third person perspective in the config file if you prefer that.
