### ISSUE TITLE
[BUG] [1.18.2] Crosshair moves incorrectly on high resolution screen

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [Exopandora/ShoulderSurfing#74]
**Describe the bug**
The crosshair moves to nonsense position when aiming.
My device: [Macbook Pro 16" 2021](https://support.apple.com/kb/SP858?locale=en_GB)  + [QHD external display](https://www.displayspecifications.com/en/model/06291c)

When fullscreen aiming on external display (2560x1440):
![2022-05-06_10 47 51](https://user-images.githubusercontent.com/4989469/167099225-9e685854-6365-40f0-a232-ff90b63c437d.png)

When fullscreen aiming on MacBook Pro display (3456x2234):
![2022-05-06_10 48 08](https://user-images.githubusercontent.com/4989469/167099242-789505ee-65e7-4d8b-9901-4e2429e856a7.png)

**To Reproduce**
1. Aim with bow.

**Expected behavior**
Crosshair moving consistently.

**Other mods**
Optifine + Shaders.

**Comment by Exopandora** [comment]
Is this isssue still present without optifine? If not please provide your shader and shader settings (render resolution, etc).

**Comment by ZsoltMolnarrr** [comment]
This issue is present without Optifine.
Rendered in full screen mode in MacBook Pro display (3456x2160).
![2022-05-06_16 35 31](https://user-images.githubusercontent.com/4989469/167154801-c26ba819-1486-4e53-aac1-896d05976c4e.png)
![2022-05-06_16 38 05](https://user-images.githubusercontent.com/4989469/167155292-ca4ddb35-2a6e-4b1c-8840-8d7b2a229428.png)

**Comment by Exopandora** [comment]
I can't reproduce this issue but i made some adjustments if it makes any difference (the jar file is zipped and needs to be upacked prior to use).
[ShoulderSurfing-1.18.2-2.2.3-beta.jar.zip](https://github.com/Exopandora/ShoulderSurfing/files/8641935/ShoulderSurfing-1.18.2-2.2.3-beta.jar.zip)

**Comment by Exopandora** [comment]
I pushed a new version with a potential fix alongside another fix.

**Comment by ZsoltMolnarMBH** [comment]
Hello!
I tested the latest release version, and the issue seems to be fixed.
Thank you!
