### ISSUE TITLE
Shoulder Surfing 1.19 Release labelled as Fabric, but doesnt work on Fabric?

### ISSUE THREAD

**Issue by Lucipo** [Exopandora/ShoulderSurfing#77]
Wondering if it was meant to be labelled as a Forge Release since all previous releases are as well. Doesnt work or even show up in mod menu using fabric nor has any functionality. 

Latest release of Fabric and Minecraft and Mod

**Comment by Exopandora** [comment]
Sorry that was a mistake. Shoulder Surfing is currently only available for Forge.
