### ISSUE TITLE
[1.12.2] Compatibility issues with 'Better HUD'

### ISSUE THREAD

**Issue by ainlzj** [Exopandora/ShoulderSurfing#78]
![1657422347359 00_00_00-00_00_30](https://user-images.githubusercontent.com/66135518/178129731-94ec9a97-e3e6-4943-b0bf-3d4bc5696684.gif)

The HUD offset of most of the modules under the dynamic crosshair is 1.12.2 .
There won't be any HUD offset with a fixed reticle view or with dynamic reticle turned off

**Comment by Exopandora** [comment]
What other mods are you using?

**Comment by Exopandora** [comment]
Please provide a list of all the mods you are using

**Comment by ainlzj** [comment]
![HK(TG%W_4BDIBI{RKXH9M@T](https://user-images.githubusercontent.com/66135518/178139003-47d4c4b7-3ca7-44ef-8550-8c79cd926134.png)
The front is my Mandarin, the back is the module name

**Comment by Exopandora** [comment]
Could you please provide me the names of the affected mods.

**Comment by ainlzj** [comment]
> 

First Aid
better HUd

**Comment by ainlzj** [comment]
![image](https://user-images.githubusercontent.com/66135518/178139280-e2a3930c-4bf4-4c0b-9e13-8c8ad56cad27.png)

**Comment by ainlzj** [comment]
vanilla inter

**Comment by Exopandora** [comment]
The bug is caused by 'Better HUD' but I don't know if this is fixable.

**Comment by Exopandora** [comment]
'Better HUD' is programmed in a way that makes this unfixable.
