### ISSUE TITLE
its doesnt have a version called 1.16.5 fabric.

### ISSUE THREAD

**Issue by wastaken90** [Exopandora/ShoulderSurfing#81]
1.16.5 is needed for it.
its a really good mod people who have low end pc and can only run 1.16.5 should have this 1.16.5 version of fabric

**Comment by Exopandora** [comment]
You can always just run the forge version

**Comment by wastaken90** [comment]
i just wanted to say bcz it wouldve completed my fabric mod collection and the mod is very good if u could port it i would be thankful.

**Comment by wastaken90** [comment]
does this need that forge port thingy?

**Comment by Exopandora** [comment]
Everything that is listed below "Required Dependency", so yes.
