### ISSUE TITLE
[BUG] [1.18.2 Forge] Aiming with a bow doesn't shoot where you look

### ISSUE THREAD

**Issue by INooBTooMuch** [Exopandora/ShoulderSurfing#86]
**Describe the bug**
When shooting it is not aimed correctly

**To Reproduce**
1. Aim from third person view
2. Shoot

**Expected behavior**
It should shoot where it is aiming. I know that moving the player to look at the crosshair breaks server compatibility but I don't know if this is the same with aiming.

**Additional information**
If this is fixable without breaking the compatibility then great. If it isn't then maybe making certain parts of the mod only work if it also is downloaded in the server would fix this and then adding the "player looking to the crosshair" would be possible.
I mention this because I believe [Apple Skin](https://www.curseforge.com/minecraft/mc-mods/appleskin) has some similar mechanic. (I'm not sure though)

**Comment by Exopandora** [comment]
Please fill in all the details. The template exists for a reason.

**Comment by INooBTooMuch** [comment]
> Please fill in all the details. The template exists for a reason.

sorry I just pressed enter by mistake while writing the title

**Comment by Exopandora** [comment]
This is why the crosshair is "adaptive" by default. If you hold a bow it will automatically change the crosshair mode from "static" (does not move) to "dynamic" (moves the crosshair onscreen to the position you are aiming at). Implementing this as an optional feature can technically be done but its not in my interest. It could also confuse players as the experience can be quite different depending on the environment.

**Comment by INooBTooMuch** [comment]
Oh I didn't see that, thnx

**Comment by Exopandora** [comment]
You can also configure the mod to go in first person when aiming.
