### ISSUE TITLE
[BUG] [Fabric] 1.18.1 releases call for "Fabric API 47.8" which are for 1.18.2

### ISSUE THREAD

**Issue by StunnerPony** [Exopandora/ShoulderSurfing#87]
### Description

Shoulder Surfing versions 2.2.9 through 2.2.11 don't work on 1.18.1 (even though they are listed as compatible for it on Curseforge) since the mod is calling for Fabric API 47.8 or higher, but the latest 1.18.1 release of Fabric API is 46.6. Version 47.8 will NOT work on Minecraft 1.18.1

### Steps to Reproduce

- Running` Fabric Loader 0.14.9 and Fabric API 0.46.6. (Both are the latest releases for 1.18.1)
- Shoulder Surfing versions 2.2.9 through 2.2.11 
- All of them spit out the same error message, calling for Fabric API 47.8 or higher.
- Tried running Fabric API 47.8
- Error message calls for Minecraft 1.18.2

### Expected Behavior

Versions listed on Curse for 1.18.1 should not require a Fabric API that only works for 1.18.2

### Screenshots

![Fabric API](https://user-images.githubusercontent.com/112061622/186593385-cf278d9b-aba4-47c4-b35c-bbcc6c03bc41.png)

### Game Logs

https://gist.github.com/StunnerPony/b5a1179f4a4c3b5713d0011e3e16f4d6#file-latest-log

**Comment by Exopandora** [comment]
Thank you for the report. The existing versions are now labeled correctly and i will publish a new version very soon that will be compatible with all 1.18 versions.
