### ISSUE TITLE
[BUG] [1.19] Opening config menu crashes game

### ISSUE THREAD

**Issue by juggins0** [Exopandora/ShoulderSurfing#88]
### Description

Trying to open the config menu for the mod crashes the game, with the Mod Menu and Forge API Config mods probably being the issue (according to Not Enough Crashes). Opening the settings menus for all the other mods works, it's just this one that crashes the game. I tried an older 1.19 version and the latest version for 1.19.2 and both had the same issue.

### Steps to Reproduce

1. Install Forge API Config, Mod Menu, and Shoulder Surfing (versions listed in "Other Mods") on top of the Fabulously Optimized Modpack.
2. Open the game and go into the mods menu.
3. Click on the configuration menu icon for Shoulder Surfing.
4. :( Crash

### Expected Behavior

The menu should open for Shoulder Surfing, allowing me to edit settings like crosshair type. 

### Screenshots

![Screenshot 2022-08-30 221239](https://user-images.githubusercontent.com/112536426/187597482-3ac28081-a661-410a-8e16-623719a89bff.png)

### Game Logs

https://gist.github.com/juggins0/725b45b71742f0b266cc0c94a99e3319

### Other Mods

(ForgeConfigAPIPort-v4.2.4-1.19.2-Fabric.jar), (modmenu-4.0.4.jar), (ShoulderSurfing-Fabric-1.19-2.2.7.jar), (ShoulderSurfing-Fabric-1.19.2-2.2.12.jar)

### Additional Information

I do have these mods installed on top of the Fabulously Optimized modpack, though I doubt mods like Sodium caused this. I also have some client-side mods such as Better Third Person, Visuality, and others that just add small QOL features and particles.

**Comment by Exopandora** [comment]
Thank you for the report. This was an issue with your specific version of ForgeConfigAPIPort. You can either update to the latest version of ForgeConfigAPIPort or use version 4.2.0 to fix the crash.
