### ISSUE TITLE
[BUG] [1.16.5] Interacting with Liquids in First Person

### ISSUE THREAD

**Issue by SisterVersio** [Exopandora/ShoulderSurfing#89]
### Description

On an otherwise unmodified game, Shoulder Surfing seems to want to use the position of the third person crosshair for placing and grabbing liquids in buckets, regardless of if you're in third person mode or not. Water ends up on the wrong block, varying from one block off to completely behind the player. The same problem happens with trying to pick it back up again. Using the Shoulder Surfing camera works as intended.

### Steps to Reproduce

1. Install mod
2. Create or load a singleplayer world in 1.16.5 [Forge 36.2.39]
2. Attempt to place water from a bucket, while in first person mode
3. See error - water is not placed where it is expected

### Expected Behavior

Water is expected to be placed in the area the crosshair is pointed towards.

### Screenshots

Water placed in first person:
![2022-09-08_09 10 15](https://user-images.githubusercontent.com/25148746/189159033-5722b5dc-9468-46b7-b10c-45224e9a4264.png)

Third person crosshair lines up with where the water ended up:
![2022-09-08_09 10 34](https://user-images.githubusercontent.com/25148746/189159078-bcfdc098-40c1-4b17-bcea-0a996d4fb641.png)

### Game Logs

https://gist.github.com/SisterVersio/ce22c7db84276cd4b399c63158b62ac6

**Comment by Exopandora** [comment]
Thank you for the report
