### ISSUE TITLE
MoBends Compatibility Issue (Crosshair offset to the left)

### ISSUE THREAD

**Issue by Eddi2015** [Exopandora/ShoulderSurfing#9]
I installed the mod alongside others and noticed that the corosshair is not changed, so I looked in the Minecraft log and found those two lines:

```
[18:17:25] [main/ERROR] [Shoulder Surfing]: Only found 9 code injections, but expected 8
[18:17:25] [main/ERROR] [Shoulder Surfing]: ShoulderSurfing should be disabled!
```

IMO it doesn't make sense that it says it *only* found 9, but expected 8. 9 is more than 8, so why does it say 'only'?

**Comment by Exopandora** [comment]
The issuse said "Crosshair not changed". Was it only the message that you reported ?

**Comment by Eddi2015** [comment]
Just looked at my debug.log and found this (maybe it has to do with the issue):

`[18:16:59] [main/INFO] [mixin]: A re-entrant transformer '$wrapper.com.teamderpy.shouldersurfing.asm.ShoulderTransformations' was detected and will no longer process meta class data`

A short time later the coremod is being excluded:

`[18:16:59] [main/DEBUG] [mixin]:   Excluding: $wrapper.com.teamderpy.shouldersurfing.asm.ShoulderTransformations`

Okay... I found the part posted above in the debug log (contains a bit more details):

```
[18:17:25] [main/TRACE] [FML]: Sending event FMLPostInitializationEvent to mod shouldersurfing
[18:17:25] [main/ERROR] [Shoulder Surfing]: Only found 9 code injections, but expected 8
[18:17:25] [main/ERROR] [Shoulder Surfing]: ShoulderSurfing should be disabled!
[18:17:25] [main/TRACE] [FML]: Sent event FMLPostInitializationEvent to mod shouldersurfing
[18:17:25] [main/DEBUG] [FML]: Bar Step: PostInitialization - Shoulder Surfing took 0.000s
```

**Comment by Eddi2015** [comment]
Oh wait I'm silly, I mean the character model not the crosshair.

**Comment by Exopandora** [comment]
"Only found 9 code injections, but expected 8" was just an oversight from me. There is a hardcoded number of modifications and i forgot to update it. And what do you mean by "Character model not changed" ? This mod does not modify the character model.

**Comment by Exopandora** [comment]
If you mean the view is not offset you can change it by pressing I, J, K, L.

**Comment by Eddi2015** [comment]
Ok. I looked at my controls menu and there are no such keys. Anyway, maybe you have not registered any to be displayed there. Pressing I, J, K or L doesn't do anything. Note: I am using Mo' Bends maybe this causes incompatibility, though I saw a youtube video where someone uses both mods at the same time like me. In general it looks like none of the features of the mod are loaded (keybinds, character shifting etc).

**Comment by Eddi2015** [comment]
What I noticed when switching the different F5 modes is that there are two modes where you can see your character from the back. I tried the keybinds (I, J, K and L) on both modes, but unfortuneately none of them worked. The charcter is not being shifted, it stays centered.

**Comment by Exopandora** [comment]
If you mean the ...
... crosshair is always centered: Turn on dynamic crosshair in the mod options
... character is always centered: Use I, J, K, L or the mod options to change the offset

If you are using shaders:
Switch to (internal) and set "Render Resolution" to 1.0x and switch back to "OFF"

If none of the steps listed fix your problem **you** are doing something wrong because the mod works as intended with MoBends (with Forge and Optifine)

**Comment by Eddi2015** [comment]
So my problem is that the character is always centered. Again: I,J,K,L don't work. Nothing is changed. I'm not sure which key in the mod options changes the offset. And yes I'm using shaders, but I don't want to turn them off. I don't think shaders are the problem. Here's a screenshot, where you can clearly see that the character is centered and not shifted to the left.
![2018-11-30_16 35 56](https://user-images.githubusercontent.com/36605424/49298789-7cd38280-f4be-11e8-994f-b6b821442267.png)

**Comment by Exopandora** [comment]
So you are CLEARLY using more than just shaders. Can i get a list of your mods ?

**Comment by Eddi2015** [comment]
![screenhotrealisticmods-crunch](https://user-images.githubusercontent.com/36605424/49395704-89164480-f737-11e8-8cc6-8b259dd01ca4.png)
Using MultiMC (This shouldn't be the problem)

Also the NoCubes mod for 1.12.2 is available on Github. If you need a link just tell me (or look at my repos as I forked it).

**Comment by Exopandora** [comment]
Sorry it took so long but have you isolated a mod that causes the crosshair not to offset (its probably an incompatibility issue)
