### ISSUE TITLE
[1.16.5] [COMPATIBILITY] Crosshair does not render when spiffy-hud is installed

### ISSUE THREAD

**Issue by DenilsonNM** [Exopandora/ShoulderSurfing#90]
### Description

the crosshair is not shown in all the cameras that use third person, even if I change to "always" in the configuration, neither when changing the type of crosshair, it only shows in first person.
It is very strange since I played with the version "shoulderSurfing-Forge-2.2.12" and everything was perfect, 
until I had the bug of the liquids that were placed as if it were in third person, so I updated the mod to version "2.2.13" and this happened, in addition to also updating the version of forge from "1.16. 5-forge-36.2.34" to version "1.16.5-forge-36.2.39" and nothing changed.

finally I went back to the previous version of shouldersurfing and the problem continued, I even went back to the previous version of forge just as it started, where everything was fine, but the problem continued, it's very strange!

### Steps to Reproduce

1. play on 1.16.5 and forge 36.2.34
2. shoulder surfing 2.2.12
3. (randomly I guess) having the bug of the liquids
4. update shouldersurfing to 2.2.13
5. bug crosshair dont show
6. update forge to 36.2.39
7. continuous bug
8. delete the config file and go back to shouldersurfing 2.2.12
9. continuous bug
10. return to forge 36.2.34
11. continuous bug
notes: (including creating a new world)

### Expected Behavior

that the crosshair is shown in 3rd person, and that it obeys the configuration

### Screenshots

FP
![2022-09-15_19 12 48](https://user-images.githubusercontent.com/57024405/190535308-00da5b2b-d9ae-4a40-9cf7-0b374e931d3b.png)
 TP
![2022-09-15_19 12 53](https://user-images.githubusercontent.com/57024405/190535347-e4fa0541-31b3-4e0f-965c-8313a6766f03.png)

### Game Logs

https://gist.github.com/DenilsonNM/e8a398f77e3bf52b2168fde3f0368f7c

### Other Mods
maybe
better third person
Optifine
inventory hud
spiffyhud

**Comment by Exopandora** [comment]
The problem is that Spiffy-HUD entirely replaces the ingame gui (including the crosshair). While doing that it does not fire any forge event whatsoever, so in the end its a bug of Spiffy-HUD.
