### ISSUE TITLE
[BUG] [Forge 1.18.2] Weird GUI glitch when using dynamic crosshair

### ISSUE THREAD

**Issue by Khudyakov1** [Exopandora/ShoulderSurfing#91]
### Description

When using **Combat Roll** for **Forge 1.18.2** together with **Better Third Person 1.8.1** and **Shoulder Surfing 1.18.2-2.2.12** the GUI element designed to show the amount of rolls left has a weird issue where it's background moves around the screen with the crosshair.

### Steps to Reproduce

No special steps needed, just install the mods together

### Expected Behavior

Expected the background to stay behind the arrows.

### Screenshots

![image](https://user-images.githubusercontent.com/74903224/191840981-96d8b733-b7f1-4272-95b5-bbc8e8d1b113.png)

### Game Logs

https://gist.github.com/Khudyakov1/726898129254a0127a32ab6ecdc4bd04

### Additional Information

The HUD widget renderer logic can be found here: https://github.com/ZsoltMolnarrr/CombatRoll/blob/1.18.2/common/src/main/java/net/combatroll/client/gui/HudRenderHelper.java

**Comment by Exopandora** [comment]
This is not a bug of ShoulderSurfing but a bug of Combat Roll. I created a PR to fix this issue over [here](https://github.com/ZsoltMolnarrr/CombatRoll/pull/7).
