### ISSUE TITLE
[BUG] [1.7.10]Crash on worldgen with SereneSeasons-1.7.10-1.2.18

### ISSUE THREAD

**Issue by SegoItCh** [Exopandora/ShoulderSurfing#93]
### Description

This mod somehow crash game with Serene Seasons

### Steps to Reproduce

Generate world

### Expected Behavior

Generated world?

### Game Logs

https://gist.github.com/SegoItCh/4872fbc94a38bcb7d1e3bf03113aadec

**Comment by Exopandora** [comment]
In the logs it looks like Biomes'o'Plenty is crashing your game. Anyways, as stated [here](https://github.com/Exopandora/ShoulderSurfing/issues/71#issuecomment-1033072909) it is currently not possible to develop forge mods for 1.7.10.

**Comment by SegoItCh** [comment]
There is a way to create workspaces, gregtech developer can help

**Comment by SegoItCh** [comment]
./gradlew --refresh-dependencies setupDecompWorkspace build eclipse

**Comment by Exopandora** [comment]
Last time i checked the servers for the required mcp mappings were taken offline. But anyways the crash is not caused by ShoulderSurfing.

**Comment by SegoItCh** [comment]
This mods won't be updated for sure, and it not crashing w/o Shoulder Surfing

**Comment by Exopandora** [comment]
It crashes on some terrain generation code caused by biomes'o'plenty. ShoulderSurfing has nothing to do with terrain gen.

**Comment by SegoItCh** [comment]
Still causes game crash with your + biome mod

**Comment by Exopandora** [comment]
As expected, shoulder surfing works just fine with biomes'o'plenty (the mod that causes the crash according to the logs you provided).

![SSR+BOP](https://user-images.githubusercontent.com/18708736/195984462-98ebcec1-49e5-4e7c-a08d-e53c2fdf8e3d.png)

Nevertheless i got working development workspace now.

**Comment by SegoItCh** [comment]
Now add SereneSeasons-1.7.10-1.2.18, and I don't use BoP world preset tho

**Comment by SegoItCh** [comment]
Hmm, actually it's something else more, I'll investigate

**Comment by SegoItCh** [comment]
So actually it's ShoulderSurfing-1.7.10-2.2.3 + SereneSeasons-1.7.10-1.2.18 + falsetweaks-mc1.7.10-2.0.0-beta0003 and it's libs(falsepatternlib-mc1.7.10-0.10.13 + 00gasstation-mc1.7.10-0.3.5)
If I delete one of them - it's just works 
Do you have Discord?

**Comment by Exopandora** [comment]
After further investigation it looks like gasstation messes up classloading in a real bad way and there is nothing i can do about it. If i am correct, the game should also crash with other coremods (not just shoulder surfing). Though this may be influenced by the order in which the mods load.

**Comment by SegoItCh** [comment]
So gasstation breaks your mod?

**Comment by Exopandora** [comment]
I think so. And in theory it should also break other (core-)mods.

**Comment by SegoItCh** [comment]
Can you make detail report to them?

**Comment by Exopandora** [comment]
Well, its complicated and i do not understand it fully yet

**Comment by SegoItCh** [comment]
Report at least something since they support 1.7.10 now

**Comment by Exopandora** [comment]
Finally found the issue. It was a classloading issue that only happens with this specific setup and two different mixin versions. While i am at it i will also update the 1.7.10 version to the latest featureset (2.2.13). You can expect an update in the coming week.

**Comment by Exopandora** [comment]
A new version can now be found on curseforge

**Comment by SegoItCh** [comment]
Thicc, do you have discord?

**Comment by Exopandora** [comment]
why?

**Comment by SegoItCh** [comment]
To ask about modding

**Comment by Exopandora** [comment]
Post yours, i will add you. In advance: i will not develop mods for you.

**Comment by SegoItCh** [comment]
Sego#3180
