### ISSUE TITLE
[FEATURE] [1.19.2 Fabric] Compatibility with AutoThirdPerson

### ISSUE THREAD

**Issue by dehen** [Exopandora/ShoulderSurfing#95]
**Describe your feature**
I love this mod, I just wished it had compatibility with AutoThirdPerson for Fabric [[git](https://github.com/quat1024/AutoThirdPerson)].

Even with Shoulder Surfing having "Replace Default Perspective" ticked, AutoThirdPerson still targets the default 3rd person perspective, instead of the shoulder cam. This is a bummer, because I'd like having a shouldercam autotrigger as I swim.

I didn't know which issue tracker this would belong to, so I probably [posted it](https://github.com/quat1024/AutoThirdPerson/issues/6) to both.

**Comment by Exopandora** [comment]
This might actually a bug of SSR. I will look into this tomorrow.

**Comment by dehen** [comment]
Thanks so much! That was so fast.

**Comment by Exopandora** [comment]
A new version will be available later today on curseforge. You can of course build the mod yourself if you want to use it immediately.
