### ISSUE TITLE
Issue with Extra Origins (Fabric) and/or Pehkui

### ISSUE THREAD

**Issue by Kryllex** [Exopandora/ShoulderSurfing#96]
When playing the Inchling origin or similarly using pehkui comands to resize the player, the player model becomes invisible when using the shoulder surfing 3rd person perspective (but not regular third person)

**Comment by Exopandora** [comment]
This might be due to the option `keep_camera_out_of_head`. It disables the player model rendering when the camera gets too close to the player.
