### ISSUE TITLE
[BUG] [1.12.2] camera clips walls allowing for x-ray

### ISSUE THREAD

**Issue by Shivaxi** [Exopandora/ShoulderSurfing#97]
### Description

Seems at certain angles, the camera clips through walls, allowing for x-ray.

### Steps to Reproduce

works best when camera is set to further distances.  walk up against a wall or corner and rotate until camera clips through.  pretty consistent.

### Expected Behavior

camera will clip through the wall allowing you to x-ray.  this doesn't happen with the vanilla 3rd person camera

### Screenshots

![2022-12-15_13 36 30](https://user-images.githubusercontent.com/10459358/207940635-ab6e138d-af00-4b25-ac08-ba01bb1593c6.png)

### Game Logs

no logs

**Comment by Exopandora** [comment]
What camera offsets and what resolution are you using?

**Comment by Shivaxi** [comment]
I'm fullscreen, 1440p, and this seems to happen with any camera settings, but works better the further you position the camera away from the player
