### ISSUE TITLE
[BUG] [1.18.2] Visual Bug with Champions Mod

### ISSUE THREAD

**Issue by INooBTooMuch** [Exopandora/ShoulderSurfing#99]
### Description

[Champions](https://www.curseforge.com/minecraft/mc-mods/champions) adds mobs with health bars on scree and having Dynamic Crosshair kind of doubles it.

### Steps to Reproduce

1. Spawn/Find a Champions mob
2. Have Dynamic Crosshair

### Expected Behavior

The second "moving" bar shouldn't be there

### Screenshots

![2022-12-23_18 33 03](https://user-images.githubusercontent.com/107572028/209368454-44b7de24-8233-43ea-b751-c6331fa52e04.png)
![2022-12-23_18 33 23](https://user-images.githubusercontent.com/107572028/209368489-4d923ff2-b8fb-46ee-90b6-83e20045b9ce.png)

### Game Logs

I don't think this is needed but [here](https://gist.github.com/INooBTooMuch/71adca7f007d673a81961921995c0220)

### Other Mods

champions-forge-1.18.2-2.1.6.1

### Additional Information

Versions
Minecarft : 1.18.2
Forge : 40.1.92
Soulder Surfing : 2.2.17

If this isn't able to be fixed (or caused) by your end then I can report this to Champions.

**Comment by Exopandora** [comment]
Thanks for the report! Champions is not using the forge events correctly here. I will open an issue with a more detailed description on how to fix this issue in their repo tomorrow.

**Comment by Exopandora** [comment]
Should be fixed on champions' side. Feel free to reopen this thread if the issue persists.
